import { useMemo, useState } from 'react';
import { Alert, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as ImagePicker from 'expo-image-picker';

const HEALTH_HERO_IMAGE = require('./assets/health-care-hero.png');
const ORANGE = '#ff7a00';
const RECORD_TYPES = ['Health Check', 'Injury', 'Illness', 'Treatment', 'Vaccination', 'Medication'];
const SEVERITIES = ['Routine', 'Monitor', 'Urgent'];
const FOLLOW_UP_OPTIONS = ['In 3 days', 'In 7 days', 'In 14 days', 'In 30 days'];
const TYPE_ICONS = { 'Health Check': 'stethoscope', Injury: 'bandage', Illness: 'thermometer-alert', Treatment: 'medical-bag', Vaccination: 'needle', Medication: 'pill' };
const DEFAULT_TITLES = { 'Health Check': 'Routine health check', Injury: 'Injury observed', Illness: 'Illness observed', Treatment: 'Treatment provided', Vaccination: 'Vaccination record', Medication: 'Medication record' };

function normalizeDate(date) { return new Date(date.getFullYear(), date.getMonth(), date.getDate()); }
function parseRecordDate(value) { const parsed = value ? new Date(value) : new Date(); return Number.isNaN(parsed.getTime()) ? normalizeDate(new Date()) : normalizeDate(parsed); }
function HeaderButton({ onPress }) { return <Pressable accessibilityLabel="Back to health and care" onPress={onPress} style={({ pressed }) => [styles.headerButton, pressed && styles.pressed]}><Ionicons name="arrow-back" size={21} color="#eef1f2" /></Pressable>; }
function formatDate(date) { return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(date); }

function DropdownField({ icon, label, value, options, open, onToggle, onSelect, renderOption }) {
  return <View style={[styles.fieldCard, open && styles.fieldCardOpen]}><Pressable onPress={onToggle} style={({ pressed }) => [styles.fieldTrigger, pressed && styles.rowPressed]}><View style={styles.fieldIcon}><MaterialCommunityIcons name={icon} size={20} color={ORANGE} /></View><View style={styles.fieldCopy}><Text style={styles.fieldLabel}>{label}</Text><Text numberOfLines={1} style={[styles.fieldValue, !value && styles.placeholder]}>{value || `Select ${label.toLowerCase()}`}</Text></View><Ionicons name={open ? 'chevron-up' : 'chevron-down'} size={18} color="#899397" /></Pressable>{open && <View style={styles.dropdownList}>{options.map((option) => { const optionValue = typeof option === 'string' ? option : option.name; return <Pressable key={typeof option === 'string' ? option : option._recordKey || option.farmBuzzId || option.name} onPress={() => onSelect(option)} style={({ pressed }) => [styles.dropdownRow, pressed && styles.rowPressed]}>{renderOption ? renderOption(option) : <Text style={[styles.dropdownText, optionValue === value && styles.dropdownTextSelected]}>{optionValue}</Text>}{optionValue === value && <Ionicons name="checkmark" size={18} color={ORANGE} />}</Pressable>; })}</View>}</View>;
}

function DateField({ value, open, onToggle, onChange }) {
  const today = normalizeDate(new Date());
  const [month, setMonth] = useState(() => new Date(value.getFullYear(), value.getMonth(), 1));
  const days = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate();
  const cells = [...Array.from({ length: month.getDay() }, (_, index) => ({ key: `blank-${index}` })), ...Array.from({ length: days }, (_, index) => { const date = new Date(month.getFullYear(), month.getMonth(), index + 1); return { key: date.toISOString(), date }; })];
  return <View style={[styles.fieldCard, open && styles.fieldCardOpen]}><Pressable onPress={onToggle} style={({ pressed }) => [styles.fieldTrigger, pressed && styles.rowPressed]}><View style={styles.fieldIcon}><MaterialCommunityIcons name="calendar-month-outline" size={20} color={ORANGE} /></View><View style={styles.fieldCopy}><Text style={styles.fieldLabel}>Record Date</Text><Text style={styles.fieldValue}>{formatDate(value)}</Text></View><Ionicons name={open ? 'chevron-up' : 'chevron-down'} size={18} color="#899397" /></Pressable>{open && <View style={styles.calendarPanel}><View style={styles.calendarHeader}><Pressable onPress={() => setMonth((current) => new Date(current.getFullYear(), current.getMonth() - 1, 1))} style={styles.calendarNav}><Ionicons name="chevron-back" size={18} color="#c2c9cb" /></Pressable><Text style={styles.calendarMonth}>{new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).format(month)}</Text><Pressable disabled={month.getTime() >= new Date(today.getFullYear(), today.getMonth(), 1).getTime()} onPress={() => setMonth((current) => new Date(current.getFullYear(), current.getMonth() + 1, 1))} style={styles.calendarNav}><Ionicons name="chevron-forward" size={18} color="#c2c9cb" /></Pressable></View><View style={styles.weekdays}>{['S', 'M', 'T', 'W', 'T', 'F', 'S'].map((day, index) => <Text key={`${day}-${index}`} style={styles.weekday}>{day}</Text>)}</View><View style={styles.calendarGrid}>{cells.map((cell) => { if (!cell.date) return <View key={cell.key} style={styles.dayCell} />; const disabled = cell.date > today; const selected = cell.date.getTime() === value.getTime(); return <Pressable key={cell.key} disabled={disabled} onPress={() => { onChange(cell.date); onToggle(); }} style={[styles.dayCell, selected && styles.daySelected]}><Text style={[styles.dayText, disabled && styles.dayDisabled, selected && styles.dayTextSelected]}>{cell.date.getDate()}</Text></Pressable>; })}</View></View>}</View>;
}

function RecordPreview({ bird, type, severity, title }) {
  return <View style={styles.preview}>{bird ? <Image source={bird.image} style={styles.previewImage} contentFit="cover" cachePolicy="memory-disk" /> : <View style={styles.previewPlaceholder}><MaterialCommunityIcons name="bird" size={26} color="#6f7b7f" /></View>}<View style={styles.previewCopy}><Text style={styles.previewEyebrow}>HEALTH RECORD PREVIEW</Text><Text numberOfLines={1} style={styles.previewTitle}>{title.trim() || type}</Text><Text numberOfLines={1} style={styles.previewMeta}>{bird?.name || 'Select a bird'} - {type}</Text></View><View style={styles.previewSeverity}><Text style={styles.previewSeverityText}>{severity}</Text></View></View>;
}

export default function AddHealthRecordScreen({ birds = [], initialBird = null, initialRecord = null, initialType = 'Health Check', onBack, onComplete }) {
  const { width } = useWindowDimensions(); const compact = width < 480; const narrow = width < 390;
  const initialRecordType = initialRecord?.type || initialType;
  const [bird, setBird] = useState(initialBird); const [type, setType] = useState(initialRecordType); const [severity, setSeverity] = useState(initialRecord?.severity || 'Routine'); const [title, setTitle] = useState(initialRecord?.title || DEFAULT_TITLES[initialRecordType]); const [bodyArea, setBodyArea] = useState(initialRecord?.bodyArea || ''); const [recordPhoto, setRecordPhoto] = useState(initialRecord?.photo || null); const [findings, setFindings] = useState(initialRecord?.findings || ''); const [careGiven, setCareGiven] = useState(initialRecord?.careGiven || ''); const [recordDate] = useState(() => parseRecordDate(initialRecord?.recordedDate)); const [followUp, setFollowUp] = useState(initialRecord?.followUp || false); const [followUpWhen, setFollowUpWhen] = useState(initialRecord?.followUpWhen || 'In 7 days'); const [showDetails, setShowDetails] = useState(!!initialRecord); const [openField, setOpenField] = useState(null); const [birdQuery, setBirdQuery] = useState('');
  const visibleBirds = useMemo(() => { const query = birdQuery.trim().toLowerCase(); return birds.filter((item) => `${item.name} ${item.bloodline} ${item.type}`.toLowerCase().includes(query)); }, [birdQuery, birds]);
  const canSave = !!bird && !!title.trim(); const toggleField = (field) => setOpenField((current) => current === field ? null : field);
  const choosePhoto = async () => { try { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [4, 3], quality: 0.85 }); if (!result.canceled) setRecordPhoto(result.assets[0].uri); } catch { Alert.alert('Photo unavailable', 'The photo library could not be opened.'); } };
  const takePhoto = async () => { try { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (!permission.granted) { Alert.alert('Camera permission required', 'Allow camera access to photograph the bird condition.'); return; } const result = await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [4, 3], quality: 0.85 }); if (!result.canceled) setRecordPhoto(result.assets[0].uri); } catch { Alert.alert('Camera unavailable', 'A photo could not be taken on this device.'); } };
  const save = () => { if (!canSave) { Alert.alert('Bird and title required', 'Select a bird and enter a record title.'); return; } const savedSeverity = showDetails ? severity : 'Routine'; const savedFollowUp = showDetails && followUp; const attention = savedSeverity !== 'Routine'; const followUpDays = Number.parseInt(followUpWhen, 10) || 7; onComplete({ ...initialRecord, id: initialRecord?.id || `health-${Date.now()}`, birdId: bird._recordKey || bird.farmBuzzId || bird.name, name: bird.name, breed: bird.bloodline, image: bird.image, type, icon: TYPE_ICONS[type], severity: savedSeverity, title: title.trim(), bodyArea: showDetails ? bodyArea.trim() : '', photo: showDetails ? recordPhoto : null, photoCaption: bodyArea.trim() ? `Photo of the affected ${bodyArea.trim().toLowerCase()}.` : 'Condition photo attached to this health record.', findings: findings.trim() || 'No additional notes.', careGiven: showDetails ? careGiven.trim() || 'No care provided at this visit.' : 'No care details added.', recordedDate: formatDate(recordDate), recordedBy: initialRecord?.recordedBy || 'Maria Santos', reminder: savedFollowUp, followUp: savedFollowUp, followUpWhen, followUpDays, needsAttention: attention, status: savedSeverity === 'Urgent' ? 'Urgent' : savedSeverity === 'Monitor' ? 'Review' : 'Recorded', color: ORANGE }); };
  return <View style={styles.screen}><StatusBar style="light" translucent backgroundColor="transparent" /><ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={styles.pageWrap}><View style={styles.page}><View style={[styles.hero, compact && styles.heroCompact]}><Image source={HEALTH_HERO_IMAGE} style={StyleSheet.absoluteFill} contentFit="cover" contentPosition="center" cachePolicy="memory-disk" /><LinearGradient colors={['rgba(2,7,9,0.22)', 'rgba(2,7,9,0.38)', '#03090c']} locations={[0, 0.5, 1]} style={StyleSheet.absoluteFill} /><SafeAreaView edges={['top']} style={styles.heroSafeArea}><View style={styles.heroHeader}><HeaderButton onPress={onBack} /><Text style={styles.screenTitle}>{initialRecord ? 'Edit Health Record' : 'Add Health Record'}</Text></View><View style={[styles.heroCopy, narrow && styles.heroCopyNarrow]}><Text style={[styles.farmName, narrow && styles.farmNameNarrow]}>FarmBuzz Farm</Text><Text style={styles.heroSubtitle}>{initialRecord ? 'Update this bird health record.' : 'Document health observations and care.'}</Text></View></SafeAreaView></View>
    <View style={[styles.content, narrow && styles.contentNarrow]}>
      {initialBird ? <View style={styles.selectedBird}><Image source={bird.image} style={styles.selectedBirdImage} contentFit="cover" cachePolicy="memory-disk" /><View style={styles.selectedBirdCopy}><Text style={styles.selectedBirdLabel}>HEALTH RECORD FOR</Text><Text style={styles.selectedBirdName}>{bird.name}</Text><Text style={styles.selectedBirdMeta}>{bird.bloodline}</Text></View><Ionicons name="checkmark-circle" size={20} color={ORANGE} /></View> : <View style={[styles.birdPicker, openField === 'bird' && styles.fieldCardOpen]}><Pressable onPress={() => toggleField('bird')} style={styles.fieldTrigger}><View style={styles.fieldIcon}><MaterialCommunityIcons name="bird" size={20} color={ORANGE} /></View><View style={styles.fieldCopy}><Text style={styles.fieldLabel}>Bird</Text><Text style={[styles.fieldValue, !bird && styles.placeholder]}>{bird?.name || 'Select bird from flock'}</Text></View><Ionicons name={openField === 'bird' ? 'chevron-up' : 'chevron-down'} size={18} color="#899397" /></Pressable>{openField === 'bird' && <View style={styles.birdDropdown}><View style={styles.searchBox}><Ionicons name="search" size={18} color="#8d989c" /><TextInput value={birdQuery} onChangeText={setBirdQuery} placeholder="Search flock..." placeholderTextColor="#6f7b7f" selectionColor={ORANGE} style={styles.searchInput} /></View><ScrollView style={styles.birdList} nestedScrollEnabled>{visibleBirds.map((item) => <Pressable key={item._recordKey || item.farmBuzzId || item.name} onPress={() => { setBird(item); setOpenField(null); }} style={({ pressed }) => [styles.birdRow, pressed && styles.rowPressed]}><Image source={item.image} style={styles.birdAvatar} contentFit="cover" cachePolicy="memory-disk" /><View style={styles.birdCopy}><Text style={styles.birdName}>{item.name}</Text><Text style={styles.birdBreed}>{item.bloodline}</Text></View>{bird === item && <Ionicons name="checkmark" size={18} color={ORANGE} />}</Pressable>)}</ScrollView></View>}</View>}
      <DropdownField icon="clipboard-pulse-outline" label="Record Type" value={type} options={RECORD_TYPES} open={openField === 'type'} onToggle={() => toggleField('type')} onSelect={(value) => { setType(value); setTitle(DEFAULT_TITLES[value]); setSeverity('Routine'); setFollowUp(false); setShowDetails(false); setOpenField(null); }} />
      <View style={styles.textCard}><View style={styles.fieldIcon}><MaterialCommunityIcons name="text-box-edit-outline" size={20} color={ORANGE} /></View><View style={styles.textCopy}><View style={styles.requiredRow}><Text style={styles.fieldLabel}>Record Title</Text><Text style={styles.required}>*</Text></View><TextInput value={title} onChangeText={setTitle} maxLength={80} placeholder="e.g. Small cut on left leg" placeholderTextColor="#6f7b7f" selectionColor={ORANGE} style={styles.titleInput} /></View></View>
      <View style={styles.notesCard}><Text style={styles.fieldLabel}>Notes (Optional)</Text><TextInput value={findings} onChangeText={setFindings} multiline textAlignVertical="top" maxLength={400} placeholder="What did you observe?" placeholderTextColor="#6f7b7f" selectionColor={ORANGE} style={styles.simpleNotesInput} /></View>
      <Pressable onPress={() => setShowDetails((current) => !current)} style={({ pressed }) => [styles.detailsTrigger, pressed && styles.rowPressed]}><View style={styles.detailsIcon}><MaterialCommunityIcons name="medical-bag" size={19} color={ORANGE} /></View><View style={styles.fieldCopy}><Text style={styles.detailsTitle}>{showDetails ? 'Hide care details' : 'Add care details'}</Text><Text style={styles.detailsText}>Severity, affected area, photo and follow-up</Text></View><Ionicons name={showDetails ? 'chevron-up' : 'chevron-down'} size={18} color="#899397" /></Pressable>
      {showDetails && <>
        <View style={styles.severityCard}><Text style={styles.fieldLabel}>Severity</Text><View style={styles.severityOptions}>{SEVERITIES.map((item) => <Pressable key={item} onPress={() => setSeverity(item)} style={[styles.severityOption, severity === item && styles.severityOptionActive]}><Text style={[styles.severityText, severity === item && styles.severityTextActive]}>{item}</Text></Pressable>)}</View></View>
        {(type === 'Injury' || type === 'Illness') && <View style={styles.textCard}><View style={styles.fieldIcon}><MaterialCommunityIcons name="crosshairs-gps" size={20} color={ORANGE} /></View><View style={styles.textCopy}><Text style={styles.fieldLabel}>Affected Area</Text><TextInput value={bodyArea} onChangeText={setBodyArea} maxLength={60} placeholder="e.g. Left leg or right wing" placeholderTextColor="#6f7b7f" selectionColor={ORANGE} style={styles.titleInput} /></View></View>}
        {(type === 'Injury' || type === 'Illness') && <View style={styles.photoCard}><View style={styles.photoHeader}><View><Text style={styles.fieldLabel}>Condition Photo</Text><Text style={styles.photoHelper}>Optional photo of the affected area</Text></View>{recordPhoto && <Pressable accessibilityLabel="Remove condition photo" onPress={() => setRecordPhoto(null)} hitSlop={8}><Ionicons name="trash-outline" size={19} color="#ff776f" /></Pressable>}</View>{recordPhoto && <Image source={recordPhoto} style={styles.conditionPhoto} contentFit="cover" contentPosition="center" />}<View style={styles.photoActions}><Pressable onPress={takePhoto} style={({ pressed }) => [styles.photoButton, pressed && styles.pressed]}><Ionicons name="camera-outline" size={19} color={ORANGE} /><Text style={styles.photoButtonText}>{recordPhoto ? 'Retake' : 'Take Photo'}</Text></Pressable><Pressable onPress={choosePhoto} style={({ pressed }) => [styles.photoButton, pressed && styles.pressed]}><Ionicons name="images-outline" size={19} color={ORANGE} /><Text style={styles.photoButtonText}>{recordPhoto ? 'Replace' : 'Choose Photo'}</Text></Pressable></View></View>}
        <View style={styles.notesCard}><Text style={styles.fieldLabel}>Care Provided (Optional)</Text><TextInput value={careGiven} onChangeText={setCareGiven} multiline textAlignVertical="top" maxLength={400} placeholder="Treatment, medication, or action taken" placeholderTextColor="#6f7b7f" selectionColor={ORANGE} style={styles.simpleNotesInput} /></View>
        <Pressable accessibilityRole="switch" accessibilityState={{ checked: followUp }} onPress={() => setFollowUp((current) => !current)} style={styles.followUpRow}><View style={styles.fieldIcon}><MaterialCommunityIcons name="calendar-refresh-outline" size={20} color={ORANGE} /></View><View style={styles.fieldCopy}><Text style={styles.fieldLabel}>Schedule Follow-up</Text><Text style={styles.followUpText}>Add this bird to Upcoming Care.</Text></View><View style={[styles.toggleTrack, followUp && styles.toggleTrackActive]}><View style={[styles.toggleThumb, followUp && styles.toggleThumbActive]} /></View></Pressable>
        {followUp && <DropdownField icon="calendar-clock-outline" label="Follow-up" value={followUpWhen} options={FOLLOW_UP_OPTIONS} open={openField === 'followup'} onToggle={() => toggleField('followup')} onSelect={(value) => { setFollowUpWhen(value); setOpenField(null); }} />}
      </>}
      <View style={styles.autoRecord}><MaterialCommunityIcons name="clock-check-outline" size={17} color={ORANGE} /><Text style={styles.autoRecordText}>{formatDate(recordDate)} - Maria Santos</Text></View>
      <View style={styles.actions}><Pressable onPress={onBack} style={({ pressed }) => [styles.cancelButton, pressed && styles.pressed]}><Text style={styles.cancelText}>Cancel</Text></Pressable><Pressable disabled={!canSave} onPress={save} style={({ pressed }) => [styles.saveButton, !canSave && styles.saveDisabled, pressed && canSave && styles.pressed]}><MaterialCommunityIcons name="content-save-outline" size={20} color="#fff" /><Text style={styles.saveText}>{initialRecord ? 'Save Changes' : 'Save Record'}</Text></Pressable></View>
    </View></View></ScrollView></View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#020709' }, pageWrap: { flexGrow: 1, alignItems: 'center', backgroundColor: '#020709' }, page: { width: '100%', maxWidth: 720, backgroundColor: '#020709' }, hero: { height: 245, overflow: 'hidden' }, heroCompact: { height: 230 }, heroSafeArea: { flex: 1 }, heroHeader: { flexDirection: 'row', alignItems: 'center', gap: 13, paddingHorizontal: 16, paddingTop: Platform.OS === 'web' ? 10 : 3 }, headerButton: { width: 40, height: 40, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(190,204,208,0.35)', backgroundColor: 'rgba(2,8,11,0.65)', alignItems: 'center', justifyContent: 'center' }, screenTitle: { color: '#f2f4f4', fontSize: 18, fontWeight: '700' }, heroCopy: { marginTop: 'auto', paddingHorizontal: 18, paddingBottom: 25 }, heroCopyNarrow: { paddingHorizontal: 11, paddingBottom: 20 }, farmName: { color: '#f5f6f6', fontSize: 32, lineHeight: 38, fontWeight: '800', fontFamily: Platform.select({ ios: 'Georgia', android: 'serif', web: 'Georgia' }), textShadowColor: 'rgba(0,0,0,0.75)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 5 }, farmNameNarrow: { fontSize: 28, lineHeight: 33 }, heroSubtitle: { marginTop: 5, color: '#c0c7c9', fontSize: 13 }, content: { paddingHorizontal: 14, paddingTop: 14, paddingBottom: 30, gap: 10 }, contentNarrow: { paddingHorizontal: 9 },
  preview: { minHeight: 76, padding: 10, borderWidth: 1, borderColor: '#5b3b14', borderRadius: 8, backgroundColor: 'rgba(255,122,0,0.045)', flexDirection: 'row', alignItems: 'center', gap: 10 }, previewImage: { width: 50, height: 50, borderRadius: 25, borderWidth: 1, borderColor: '#65400e' }, previewPlaceholder: { width: 50, height: 50, borderRadius: 25, borderWidth: 1, borderColor: '#354248', alignItems: 'center', justifyContent: 'center' }, previewCopy: { flex: 1, minWidth: 0 }, previewEyebrow: { color: ORANGE, fontSize: 7, fontWeight: '800' }, previewTitle: { marginTop: 4, color: '#edf0f1', fontSize: 13, fontWeight: '800' }, previewMeta: { marginTop: 3, color: '#839094', fontSize: 8 }, previewSeverity: { paddingHorizontal: 8, paddingVertical: 5, borderWidth: 1, borderColor: '#66400e', borderRadius: 11 }, previewSeverityText: { color: ORANGE, fontSize: 8, fontWeight: '700' },
  selectedBird: { minHeight: 68, padding: 9, borderWidth: 1, borderColor: '#563914', borderRadius: 8, backgroundColor: 'rgba(255,122,0,0.045)', flexDirection: 'row', alignItems: 'center', gap: 10 },
  selectedBirdImage: { width: 46, height: 46, borderRadius: 7, borderWidth: 1, borderColor: '#65400e' },
  selectedBirdCopy: { flex: 1, minWidth: 0 }, selectedBirdLabel: { color: ORANGE, fontSize: 7, fontWeight: '800' }, selectedBirdName: { marginTop: 3, color: '#e9edee', fontSize: 12, fontWeight: '700' }, selectedBirdMeta: { marginTop: 2, color: '#7f8b8f', fontSize: 8 },
  fieldCard: { position: 'relative', zIndex: 1, minHeight: 60, borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317', overflow: 'visible' }, fieldCardOpen: { zIndex: 100, elevation: 12, borderColor: '#69410e' }, fieldTrigger: { minHeight: 60, paddingHorizontal: 11, borderRadius: 8, flexDirection: 'row', alignItems: 'center', gap: 10 }, fieldIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,122,0,0.08)', alignItems: 'center', justifyContent: 'center' }, fieldCopy: { flex: 1, minWidth: 0 }, fieldLabel: { color: '#dfe3e4', fontSize: 10, fontWeight: '700' }, fieldValue: { marginTop: 4, color: '#c2c9cb', fontSize: 11 }, placeholder: { color: '#707c80' }, dropdownList: { position: 'absolute', top: 61, left: -1, right: -1, zIndex: 110, elevation: 14, borderWidth: 1, borderColor: '#36464d', borderRadius: 8, backgroundColor: '#081115', overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.42, shadowRadius: 14 }, dropdownRow: { minHeight: 45, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: '#1e2b31', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, dropdownText: { color: '#b7c0c2', fontSize: 11 }, dropdownTextSelected: { color: ORANGE, fontWeight: '700' }, rowPressed: { backgroundColor: '#111d22' },
  birdPicker: { position: 'relative', zIndex: 2, minHeight: 60, borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317', overflow: 'visible' }, birdDropdown: { position: 'absolute', top: 61, left: -1, right: -1, zIndex: 120, elevation: 15, maxHeight: 315, padding: 8, borderWidth: 1, borderColor: '#36464d', borderRadius: 8, backgroundColor: '#081115', shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.42, shadowRadius: 14 }, searchBox: { height: 40, paddingHorizontal: 9, borderWidth: 1, borderColor: '#28363c', borderRadius: 7, flexDirection: 'row', alignItems: 'center', gap: 7 }, searchInput: { flex: 1, height: 38, color: '#e3e7e8', fontSize: 10, outlineStyle: 'none' }, birdList: { maxHeight: 245, marginTop: 6 }, birdRow: { minHeight: 54, paddingHorizontal: 7, flexDirection: 'row', alignItems: 'center', gap: 9 }, birdAvatar: { width: 38, height: 38, borderRadius: 19 }, birdCopy: { flex: 1, minWidth: 0 }, birdName: { color: '#dce1e2', fontSize: 10, fontWeight: '700' }, birdBreed: { marginTop: 2, color: '#778286', fontSize: 8 },
  textCard: { minHeight: 66, paddingHorizontal: 11, borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317', flexDirection: 'row', alignItems: 'center', gap: 10 }, textCopy: { flex: 1 }, requiredRow: { flexDirection: 'row', gap: 3 }, required: { color: '#ff5148', fontSize: 11, fontWeight: '700' }, titleInput: { height: 35, paddingVertical: 0, color: '#e5e9ea', fontSize: 11, outlineStyle: 'none' }, severityCard: { padding: 11, borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317' }, severityOptions: { marginTop: 9, flexDirection: 'row', gap: 7 }, severityOption: { flex: 1, height: 38, borderWidth: 1, borderColor: '#2c3a40', borderRadius: 7, alignItems: 'center', justifyContent: 'center' }, severityOptionActive: { borderColor: ORANGE, backgroundColor: 'rgba(255,122,0,0.08)' }, severityText: { color: '#899599', fontSize: 10, fontWeight: '600' }, severityTextActive: { color: ORANGE }, photoCard: { padding: 11, borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317' }, photoHeader: { minHeight: 34, flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 }, photoHelper: { marginTop: 4, color: '#778387', fontSize: 8 }, conditionPhoto: { width: '100%', aspectRatio: 1.75, marginTop: 8, borderRadius: 7, backgroundColor: '#111a1e' }, photoActions: { marginTop: 9, flexDirection: 'row', gap: 8 }, photoButton: { flex: 1, height: 42, borderWidth: 1, borderColor: '#5f3c12', borderRadius: 7, backgroundColor: 'rgba(255,122,0,0.045)', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, photoButtonText: { color: '#d6dcde', fontSize: 10, fontWeight: '700' }, notesCard: { padding: 11, borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317' }, notesInput: { minHeight: 82, marginTop: 7, padding: 9, borderWidth: 1, borderColor: '#223138', borderRadius: 7, color: '#e5e9ea', fontSize: 11, outlineStyle: 'none' },
  simpleNotesInput: { minHeight: 58, marginTop: 6, paddingVertical: 7, color: '#e5e9ea', fontSize: 11, lineHeight: 16, outlineStyle: 'none' },
  detailsTrigger: { minHeight: 60, paddingHorizontal: 11, borderWidth: 1, borderColor: '#2b383e', borderRadius: 8, backgroundColor: '#0a1317', flexDirection: 'row', alignItems: 'center', gap: 10 },
  detailsIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,122,0,0.08)', alignItems: 'center', justifyContent: 'center' },
  detailsTitle: { color: '#dfe3e4', fontSize: 10, fontWeight: '700' }, detailsText: { marginTop: 3, color: '#788488', fontSize: 8 },
  calendarPanel: { position: 'absolute', top: 61, left: -1, right: -1, zIndex: 110, elevation: 14, padding: 10, borderWidth: 1, borderColor: '#36464d', borderRadius: 8, backgroundColor: '#081115', shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.42, shadowRadius: 14 }, calendarHeader: { height: 36, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, calendarNav: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' }, calendarMonth: { color: '#dce0e1', fontSize: 11, fontWeight: '700' }, weekdays: { flexDirection: 'row' }, weekday: { width: '14.2857%', paddingVertical: 5, color: '#718084', fontSize: 9, textAlign: 'center' }, calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' }, dayCell: { width: '14.2857%', aspectRatio: 1.25, borderRadius: 6, alignItems: 'center', justifyContent: 'center' }, daySelected: { backgroundColor: ORANGE }, dayText: { color: '#b9c1c3', fontSize: 10 }, dayDisabled: { color: '#3f4a4e' }, dayTextSelected: { color: '#fff', fontWeight: '800' },
  followUpRow: { minHeight: 64, paddingHorizontal: 11, borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317', flexDirection: 'row', alignItems: 'center', gap: 10 }, followUpText: { marginTop: 3, color: '#7d898c', fontSize: 8 }, toggleTrack: { width: 44, height: 25, padding: 3, borderRadius: 13, backgroundColor: '#344147' }, toggleTrackActive: { backgroundColor: ORANGE }, toggleThumb: { width: 19, height: 19, borderRadius: 10, backgroundColor: '#aeb7ba' }, toggleThumbActive: { backgroundColor: '#fff', transform: [{ translateX: 19 }] }, recorder: { minHeight: 54, paddingHorizontal: 12, borderWidth: 1, borderColor: '#2c383e', borderRadius: 8, backgroundColor: '#081115', flexDirection: 'row', alignItems: 'center', gap: 9 }, recorderLabel: { color: '#788488', fontSize: 8 }, recorderName: { marginTop: 2, color: '#c4cbcd', fontSize: 10, fontWeight: '600' },
  autoRecord: { minHeight: 30, paddingHorizontal: 4, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, autoRecordText: { color: '#788488', fontSize: 8 },
  actions: { flexDirection: 'row', gap: 8 }, cancelButton: { flex: 0.7, height: 50, borderWidth: 1, borderColor: '#2a383e', borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, cancelText: { color: '#bac2c4', fontSize: 12, fontWeight: '600' }, saveButton: { flex: 1.3, height: 50, borderRadius: 8, backgroundColor: '#f66f00', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, saveDisabled: { backgroundColor: '#3b4143', opacity: 0.65 }, saveText: { color: '#fff', fontSize: 12, fontWeight: '700' }, pressed: { opacity: 0.72 },
});
