import { Alert, Platform, Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';

const HEALTH_HERO_IMAGE = require('./assets/health-care-hero.png');
const ORANGE = '#ff7a00';

function HeaderButton({ icon, label, onPress }) {
  return <Pressable accessibilityLabel={label} onPress={onPress} style={({ pressed }) => [styles.headerButton, pressed && styles.pressed]}><Ionicons name={icon} size={21} color="#eef1f2" /></Pressable>;
}

function Fact({ icon, label, value, isLast }) {
  return <View style={[styles.fact, !isLast && styles.factDivider]}><MaterialCommunityIcons name={icon} size={21} color={ORANGE} /><Text numberOfLines={2} style={styles.factValue}>{value}</Text><Text style={styles.factLabel}>{label}</Text></View>;
}

function InformationRow({ icon, label, value, isLast }) {
  return <View style={[styles.infoRow, !isLast && styles.rowDivider]}><View style={styles.infoIcon}><MaterialCommunityIcons name={icon} size={20} color={ORANGE} /></View><View style={styles.infoCopy}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View></View>;
}

export default function HealthRecordDetailScreen({ bird, record, onBack, onEdit, onResolve, onDelete }) {
  const { width } = useWindowDimensions(); const compact = width < 480; const narrow = width < 380;
  if (!record) return <View style={styles.missing}><MaterialCommunityIcons name="clipboard-alert-outline" size={42} color="#687478" /><Text style={styles.missingText}>Health record unavailable</Text><Pressable onPress={onBack} style={styles.missingButton}><Text style={styles.missingButtonText}>Back to Health & Care</Text></Pressable></View>;
  const resolved = record.status === 'Resolved' || record.status === 'Completed';
  const severity = record.severity || 'Routine';
  const confirmDelete = () => Alert.alert('Delete health record?', 'This record will be removed from the bird health history.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: onDelete }]);
  return (
    <View style={styles.screen}><StatusBar style="light" translucent backgroundColor="transparent" /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.pageWrap}><View style={styles.page}>
      <View style={[styles.hero, compact && styles.heroCompact]}><Image source={record.photo || HEALTH_HERO_IMAGE} style={StyleSheet.absoluteFill} contentFit="cover" contentPosition="center" cachePolicy="memory-disk" /><LinearGradient colors={['rgba(2,7,9,0.22)', 'rgba(2,7,9,0.42)', '#03090c']} locations={[0, 0.5, 1]} style={StyleSheet.absoluteFill} /><SafeAreaView edges={['top']} style={styles.heroSafeArea}><View style={styles.heroHeader}><View style={styles.heroHeaderLeft}><HeaderButton icon="arrow-back" label="Back to bird health" onPress={onBack} /><Text style={styles.screenTitle}>Health Record Details</Text></View><HeaderButton icon="ellipsis-horizontal" label="Health record options" onPress={() => Alert.alert('Record options', 'Edit, resolve, or delete this health record below.')} /></View><View style={[styles.heroCopy, narrow && styles.heroCopyNarrow]}><View style={styles.typeBadge}><MaterialCommunityIcons name={record.icon || 'clipboard-pulse-outline'} size={15} color={ORANGE} /><Text style={styles.typeText}>{record.type}</Text></View><Text numberOfLines={3} style={[styles.recordTitle, narrow && styles.recordTitleNarrow]}>{record.title}</Text><Text style={styles.birdName}>{bird?.name || record.name} · {bird?.bloodline || record.breed}</Text></View></SafeAreaView></View>
      <View style={[styles.content, narrow && styles.contentNarrow]}>
        <View style={styles.facts}><Fact icon="alert-circle-outline" label="Severity" value={severity} /><Fact icon="progress-check" label="Status" value={record.status || 'Recorded'} /><Fact icon="calendar-month-outline" label="Recorded" value={record.recordedDate} isLast /></View>
        {record.photo && <View style={styles.photoPanel}><View style={styles.photoHeader}><View><Text style={styles.sectionEyebrow}>CONDITION PHOTO</Text><Text style={styles.photoTitle}>{record.bodyArea || 'Affected area'}</Text></View>{record.bodyArea && <View style={styles.areaBadge}><MaterialCommunityIcons name="crosshairs-gps" size={13} color={ORANGE} /><Text style={styles.areaText}>{record.bodyArea}</Text></View>}</View><Image source={record.photo} style={styles.conditionPhoto} contentFit="cover" contentPosition="center" cachePolicy="memory-disk" /><Text style={styles.photoCaption}>{record.photoCaption || 'Condition photo attached to this record.'}</Text></View>}
        <Text style={styles.sectionTitle}>Clinical Record</Text><View style={styles.clinicalPanel}><View style={styles.clinicalBlock}><View style={styles.clinicalHeading}><MaterialCommunityIcons name="stethoscope" size={20} color={ORANGE} /><Text style={styles.clinicalLabel}>Findings / Symptoms</Text></View><Text style={styles.clinicalText}>{record.findings || 'No findings recorded.'}</Text></View><View style={[styles.clinicalBlock, styles.clinicalDivider]}><View style={styles.clinicalHeading}><MaterialCommunityIcons name="medical-bag" size={20} color={ORANGE} /><Text style={styles.clinicalLabel}>Care Provided</Text></View><Text style={styles.clinicalText}>{record.careGiven || 'No care recorded.'}</Text></View></View>
        <Text style={styles.sectionTitle}>Record Information</Text><View style={styles.infoPanel}><InformationRow icon="account-check-outline" label="Recorded By" value={record.recordedBy || 'Farm staff'} /><InformationRow icon="crosshairs-gps" label="Affected Area" value={record.bodyArea || 'Not specified'} /><InformationRow icon="calendar-refresh-outline" label="Follow-up" value={record.followUp ? record.followUpWhen || 'Scheduled' : resolved ? 'Completed' : 'Not scheduled'} isLast /></View>
        {record.followUp && !resolved && <View style={styles.followUpPanel}><View style={styles.followUpIcon}><MaterialCommunityIcons name="calendar-clock-outline" size={24} color={ORANGE} /></View><View style={styles.followUpCopy}><Text style={styles.followUpEyebrow}>FOLLOW-UP REQUIRED</Text><Text style={styles.followUpTitle}>{record.followUpWhen || 'Follow-up scheduled'}</Text><Text style={styles.followUpText}>Check the affected area and update this record after the next observation.</Text></View></View>}
        <View style={styles.actions}><Pressable onPress={onEdit} style={({ pressed }) => [styles.secondaryButton, pressed && styles.pressed]}><MaterialCommunityIcons name="pencil-outline" size={20} color={ORANGE} /><Text style={styles.secondaryText}>Edit Record</Text></Pressable><Pressable disabled={resolved} onPress={onResolve} style={({ pressed }) => [styles.primaryButton, resolved && styles.resolvedButton, pressed && !resolved && styles.pressed]}><MaterialCommunityIcons name="check-circle-outline" size={20} color="#fff" /><Text style={styles.primaryText}>{resolved ? 'Resolved' : 'Mark Resolved'}</Text></Pressable></View>
        <Pressable onPress={confirmDelete} style={({ pressed }) => [styles.deleteButton, pressed && styles.pressed]}><Ionicons name="trash-outline" size={19} color="#ff7068" /><Text style={styles.deleteText}>Delete Health Record</Text></Pressable>
      </View>
    </View></ScrollView></View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#020709' }, pageWrap: { flexGrow: 1, alignItems: 'center', backgroundColor: '#020709' }, page: { width: '100%', maxWidth: 720, backgroundColor: '#020709' }, hero: { height: 335, overflow: 'hidden', backgroundColor: '#101719' }, heroCompact: { height: 305 }, heroSafeArea: { flex: 1 }, heroHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingTop: Platform.OS === 'web' ? 10 : 3 }, heroHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 }, headerButton: { width: 40, height: 40, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(190,204,208,0.35)', backgroundColor: 'rgba(2,8,11,0.65)', alignItems: 'center', justifyContent: 'center' }, screenTitle: { color: '#f1f3f3', fontSize: 17, fontWeight: '700' }, heroCopy: { marginTop: 'auto', paddingHorizontal: 18, paddingBottom: 27 }, heroCopyNarrow: { paddingHorizontal: 11, paddingBottom: 22 }, typeBadge: { alignSelf: 'flex-start', height: 29, paddingHorizontal: 9, borderWidth: 1, borderColor: '#67410f', borderRadius: 15, backgroundColor: 'rgba(255,122,0,0.08)', flexDirection: 'row', alignItems: 'center', gap: 5 }, typeText: { color: '#ff9a36', fontSize: 8, fontWeight: '800' }, recordTitle: { marginTop: 10, color: '#f3f5f5', fontSize: 29, lineHeight: 35, fontWeight: '800', textShadowColor: 'rgba(0,0,0,0.7)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 5 }, recordTitleNarrow: { fontSize: 24, lineHeight: 29 }, birdName: { marginTop: 6, color: '#b8c0c2', fontSize: 11 },
  content: { paddingHorizontal: 14, paddingTop: 14, paddingBottom: 32 }, contentNarrow: { paddingHorizontal: 9 }, facts: { minHeight: 101, marginBottom: 12, borderWidth: 1, borderColor: '#28353a', borderRadius: 8, backgroundColor: '#0a1317', flexDirection: 'row', overflow: 'hidden' }, fact: { flex: 1, minWidth: 0, paddingHorizontal: 5, paddingVertical: 13, alignItems: 'center', justifyContent: 'center' }, factDivider: { borderRightWidth: 1, borderRightColor: '#26343a' }, factValue: { marginTop: 6, color: '#eef1f2', fontSize: 10, fontWeight: '800', textAlign: 'center' }, factLabel: { marginTop: 3, color: '#7e898d', fontSize: 8 },
  photoPanel: { marginBottom: 18, padding: 11, borderWidth: 1, borderColor: '#5f3c11', borderRadius: 8, backgroundColor: '#0a1317' }, photoHeader: { minHeight: 43, flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 }, sectionEyebrow: { color: ORANGE, fontSize: 7, fontWeight: '800' }, photoTitle: { marginTop: 4, color: '#e5e9ea', fontSize: 12, fontWeight: '700' }, areaBadge: { minHeight: 27, paddingHorizontal: 8, borderWidth: 1, borderColor: '#69410e', borderRadius: 14, backgroundColor: 'rgba(255,122,0,0.08)', flexDirection: 'row', alignItems: 'center', gap: 4 }, areaText: { color: '#ff9a36', fontSize: 8, fontWeight: '700' }, conditionPhoto: { width: '100%', aspectRatio: 1.65, borderRadius: 7, backgroundColor: '#111a1e' }, photoCaption: { marginTop: 7, color: '#7e8a8e', fontSize: 8, lineHeight: 13 },
  sectionTitle: { marginTop: 4, marginBottom: 8, color: '#e7eaeb', fontSize: 14, fontWeight: '700' }, clinicalPanel: { marginBottom: 18, borderWidth: 1, borderColor: '#28353a', borderRadius: 8, backgroundColor: '#0a1317', overflow: 'hidden' }, clinicalBlock: { padding: 13 }, clinicalDivider: { borderTopWidth: 1, borderTopColor: '#223037' }, clinicalHeading: { flexDirection: 'row', alignItems: 'center', gap: 8 }, clinicalLabel: { color: '#dfe4e5', fontSize: 11, fontWeight: '700' }, clinicalText: { marginTop: 9, color: '#929da0', fontSize: 10, lineHeight: 17 }, infoPanel: { marginBottom: 12, borderWidth: 1, borderColor: '#28353a', borderRadius: 8, backgroundColor: '#0a1317', overflow: 'hidden' }, infoRow: { minHeight: 66, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 10 }, rowDivider: { borderBottomWidth: 1, borderBottomColor: '#223037' }, infoIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,122,0,0.08)', alignItems: 'center', justifyContent: 'center' }, infoCopy: { flex: 1 }, infoLabel: { color: '#dce1e2', fontSize: 10, fontWeight: '700' }, infoValue: { marginTop: 4, color: '#7f8b8e', fontSize: 9 },
  followUpPanel: { minHeight: 80, marginBottom: 14, padding: 11, borderWidth: 1, borderColor: '#68410e', borderRadius: 8, backgroundColor: 'rgba(255,122,0,0.055)', flexDirection: 'row', alignItems: 'center', gap: 11 }, followUpIcon: { width: 46, height: 46, borderRadius: 23, backgroundColor: 'rgba(255,122,0,0.1)', alignItems: 'center', justifyContent: 'center' }, followUpCopy: { flex: 1 }, followUpEyebrow: { color: ORANGE, fontSize: 7, fontWeight: '800' }, followUpTitle: { marginTop: 4, color: '#e6eaeb', fontSize: 11, fontWeight: '700' }, followUpText: { marginTop: 4, color: '#849094', fontSize: 8, lineHeight: 12 }, actions: { flexDirection: 'row', gap: 8 }, secondaryButton: { flex: 0.9, height: 50, borderWidth: 1, borderColor: '#68400e', borderRadius: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, secondaryText: { color: ORANGE, fontSize: 10, fontWeight: '700' }, primaryButton: { flex: 1.1, height: 50, paddingHorizontal: 8, borderRadius: 8, backgroundColor: '#f66f00', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, resolvedButton: { backgroundColor: '#3b4244', opacity: 0.75 }, primaryText: { color: '#fff', fontSize: 10, fontWeight: '700' }, deleteButton: { height: 46, marginTop: 9, borderWidth: 1, borderColor: '#572c2b', borderRadius: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, deleteText: { color: '#ff7068', fontSize: 10, fontWeight: '700' }, pressed: { opacity: 0.72 },
  missing: { flex: 1, padding: 24, backgroundColor: '#020709', alignItems: 'center', justifyContent: 'center' }, missingText: { marginTop: 12, color: '#d8ddde', fontSize: 17, fontWeight: '700' }, missingButton: { height: 44, marginTop: 18, paddingHorizontal: 18, borderRadius: 8, backgroundColor: '#f66f00', alignItems: 'center', justifyContent: 'center' }, missingButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
});
