import { Platform, Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';

const HERO_IMAGE = require('./assets/ranging-card.png');
const RANGING_IMAGE = require('./assets/ranging-card.png');
const PULLET_IMAGE = require('./assets/growing-card.png');
const ORANGE = '#ff7900';

function PathCard({ title, detail, image, icon, onPress }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={`Open ${title}`} onPress={onPress} style={({pressed}) => [styles.card,pressed && styles.pressed]}><Image source={image} style={styles.cardImage} contentFit="cover" contentPosition="center" /><LinearGradient colors={['rgba(2,7,9,.05)','rgba(2,7,9,.58)','#071014']} locations={[0,.54,1]} style={StyleSheet.absoluteFill} /><View style={styles.cardContent}><View style={styles.cardIcon}><MaterialCommunityIcons name={icon} size={23} color={ORANGE} /></View><View style={styles.cardCopy}><Text style={styles.cardTitle}>{title}</Text><Text style={styles.cardDetail}>{detail}</Text></View><View style={styles.cardArrow}><Ionicons name="chevron-forward" size={20} color="#fff" /></View></View></Pressable>;
}

export default function MaturingScreen({ onBack, onOpenRanging, onOpenFemale }) {
  const { width } = useWindowDimensions();
  const compact = width < 480;
  return <View style={styles.screen}><StatusBar style="light" translucent backgroundColor="transparent" /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.pageWrap}><View style={styles.page}><View style={[styles.hero,compact && styles.heroCompact]}><Image source={HERO_IMAGE} style={StyleSheet.absoluteFill} contentFit="cover" contentPosition="center" /><LinearGradient colors={['rgba(2,7,9,.14)','rgba(2,7,9,.34)','#03090c']} locations={[0,.5,1]} style={StyleSheet.absoluteFill} /><SafeAreaView edges={['top']} style={styles.heroSafe}><View style={styles.header}><Pressable accessibilityLabel="Back to farm" onPress={onBack} style={styles.back}><Ionicons name="arrow-back" size={21} color="#fff" /></Pressable><Text style={styles.headerTitle}>Maturing</Text></View><View style={styles.heroCopy}><Text style={styles.heroTitle}>Maturing</Text><Text style={styles.heroSubtitle}>Manage birds through their male ranging and female pullet paths.</Text></View></SafeAreaView></View><View style={styles.content}><Text style={styles.overline}>MATURING PATHS</Text><View style={styles.headingRow}><Text style={styles.sectionTitle}>Choose a group</Text><Text style={styles.pathCount}>2 groups</Text></View><View style={[styles.grid,compact && styles.gridCompact]}><PathCard title="Ranging" detail="Open-range development and selection readiness" image={RANGING_IMAGE} icon="weather-sunny" onPress={onOpenRanging} /><PathCard title="Female / Pullet" detail="Female development and future breeder groups" image={PULLET_IMAGE} icon="gender-female" onPress={onOpenFemale} /></View></View></View></ScrollView></View>;
}

const styles = StyleSheet.create({
  screen:{flex:1,backgroundColor:'#020709'},pageWrap:{flexGrow:1,alignItems:'center'},page:{width:'100%',maxWidth:720},hero:{height:250,overflow:'hidden'},heroCompact:{height:225},heroSafe:{flex:1},header:{paddingHorizontal:16,paddingTop:Platform.OS==='web'?10:3,flexDirection:'row',alignItems:'center',gap:10},back:{width:40,height:40,borderRadius:20,borderWidth:1,borderColor:'rgba(190,204,208,.35)',backgroundColor:'rgba(2,8,11,.68)',alignItems:'center',justifyContent:'center'},headerTitle:{color:'#fff',fontSize:15,fontWeight:'800'},heroCopy:{marginTop:'auto',paddingHorizontal:20,paddingBottom:24},heroTitle:{color:'#fff',fontSize:34,lineHeight:40,fontWeight:'800',fontFamily:Platform.select({ios:'Georgia',android:'serif',web:'Georgia'})},heroSubtitle:{marginTop:4,maxWidth:440,color:'#c4cccf',fontSize:11,lineHeight:16},content:{padding:16,paddingBottom:30},overline:{color:'#7c898e',fontSize:7,fontWeight:'800'},headingRow:{marginTop:4,marginBottom:10,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},sectionTitle:{color:'#eef2f3',fontSize:17,fontWeight:'800'},pathCount:{color:ORANGE,fontSize:8,fontWeight:'800'},grid:{flexDirection:'row',gap:10},gridCompact:{gap:7},card:{flex:1,minWidth:0,aspectRatio:.82,borderRadius:7,borderWidth:1,borderColor:'#2a3b42',backgroundColor:'#091317',overflow:'hidden'},cardImage:{...StyleSheet.absoluteFillObject,width:'100%',height:'62%'},cardContent:{marginTop:'auto',minHeight:108,padding:12,flexDirection:'row',alignItems:'center',gap:9},cardIcon:{width:38,height:38,borderRadius:19,borderWidth:1,borderColor:'#73420f',backgroundColor:'rgba(5,13,16,.88)',alignItems:'center',justifyContent:'center'},cardCopy:{flex:1,minWidth:0},cardTitle:{color:'#fff',fontSize:13,fontWeight:'800'},cardDetail:{marginTop:4,color:'#9aa6aa',fontSize:8,lineHeight:12},cardArrow:{width:30,height:30,borderRadius:15,backgroundColor:'rgba(255,121,0,.86)',alignItems:'center',justifyContent:'center'},pressed:{opacity:.75},
});
