import { Alert, Platform, Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { FLOCK_HERO_IMAGE } from './constants';

const ORANGE = '#ff7a00';
const ROOSTER_IMAGE = 'https://images.unsplash.com/photo-1730360037813-9777f13b88bb?auto=format&fit=crop&w=400&q=82';
const BLACK_ROOSTER_IMAGE = 'https://images.unsplash.com/photo-1551127501-d4385c7484b4?auto=format&fit=crop&w=400&q=82';
const HEN_IMAGE = 'https://images.unsplash.com/photo-1770221499235-11dd1041e181?auto=format&fit=crop&w=400&q=82';
const BROWN_HEN_IMAGE = 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&w=400&q=82';

const RAZOR_PEDIGREE = {
  sire: { name: 'Titan 006', relation: 'Sire', bloodline: 'Kelso', id: 'FBZ-2024-006', image: BLACK_ROOSTER_IMAGE, gender: 'male' },
  dam: { name: 'Amber 021', relation: 'Dam', bloodline: 'Sweater', id: 'FBZ-2024-021', image: BROWN_HEN_IMAGE, gender: 'female' },
  paternal: [
    { name: 'Red King 003', relation: 'Grandsire', bloodline: 'Kelso', id: 'FBZ-2022-003', image: ROOSTER_IMAGE, gender: 'male' },
    { name: 'Pearl 017', relation: 'Granddam', bloodline: 'Kelso', id: 'FBZ-2022-017', image: HEN_IMAGE, gender: 'female' },
  ],
  maternal: [
    { name: 'Copper 011', relation: 'Grandsire', bloodline: 'Sweater', id: 'FBZ-2022-011', image: BLACK_ROOSTER_IMAGE, gender: 'male' },
    { name: 'Honey 029', relation: 'Granddam', bloodline: 'Hatch', id: 'FBZ-2022-029', image: BROWN_HEN_IMAGE, gender: 'female' },
  ],
  composition: [{ label: 'Kelso', value: 50 }, { label: 'Sweater', value: 25 }, { label: 'Hatch', value: 25 }],
};

function getFarmBuzzId(bird) {
  if (bird.farmBuzzId) return bird.farmBuzzId;
  const ring = bird.details?.find((detail) => detail.icon === 'tag-outline')?.text || bird.name;
  const digits = ring.replace(/\D/g, '').slice(-5) || '001';
  return `FBZ-${new Date().getFullYear()}-${digits.padStart(3, '0')}`;
}

function getQrCodeUrl(value) {
  return `https://quickchart.io/qr?text=${encodeURIComponent(value)}&size=180&margin=1&dark=111111&light=ffffff`;
}

function makeFallbackPedigree(bird) {
  const base = bird.bloodline?.replace(/\s+Bloodline$/i, '') || 'Foundation';
  return {
    sire: { name: 'Sire not recorded', relation: 'Sire', bloodline: base, id: 'No FarmBuzz ID', image: BLACK_ROOSTER_IMAGE, gender: 'male', missing: true },
    dam: { name: 'Dam not recorded', relation: 'Dam', bloodline: base, id: 'No FarmBuzz ID', image: BROWN_HEN_IMAGE, gender: 'female', missing: true },
    paternal: [
      { name: 'Not recorded', relation: 'Grandsire', bloodline: 'Unknown', id: 'No record', image: ROOSTER_IMAGE, gender: 'male', missing: true },
      { name: 'Not recorded', relation: 'Granddam', bloodline: 'Unknown', id: 'No record', image: HEN_IMAGE, gender: 'female', missing: true },
    ],
    maternal: [
      { name: 'Not recorded', relation: 'Grandsire', bloodline: 'Unknown', id: 'No record', image: BLACK_ROOSTER_IMAGE, gender: 'male', missing: true },
      { name: 'Not recorded', relation: 'Granddam', bloodline: 'Unknown', id: 'No record', image: BROWN_HEN_IMAGE, gender: 'female', missing: true },
    ],
    composition: [{ label: base, value: 100 }],
  };
}

function HeaderButton({ icon, label, onPress }) {
  return <Pressable accessibilityLabel={label} onPress={onPress} style={({ pressed }) => [styles.headerButton, pressed && styles.pressed]}><Ionicons name={icon} size={21} color="#eef1f2" /></Pressable>;
}

function ParentCard({ parent }) {
  return <Pressable onPress={() => parent.missing ? Alert.alert('Parent not recorded', `Add this bird's ${parent.relation.toLowerCase()} to complete the pedigree.`) : Alert.alert(parent.name, `${parent.bloodline}\n${parent.id}`)} style={({ pressed }) => [styles.simpleParent, pressed && styles.cardPressed]}><Image source={parent.image} style={[styles.simpleParentImage, parent.missing && styles.ancestorImageMissing]} contentFit="cover" cachePolicy="memory-disk" /><Text style={styles.simpleRelation}>{parent.relation}</Text><Text numberOfLines={1} style={styles.simpleParentName}>{parent.name}</Text><Text numberOfLines={1} style={styles.simpleParentBloodline}>{parent.bloodline}</Text></Pressable>;
}

function GrandparentRow({ ancestor, branch, isLast }) {
  return <Pressable onPress={() => ancestor.missing ? Alert.alert('Ancestor not recorded', 'Add this ancestor to complete the pedigree.') : Alert.alert(ancestor.name, `${ancestor.bloodline}\n${ancestor.id}`)} style={({ pressed }) => [styles.simpleAncestorRow, !isLast && styles.rowDivider, pressed && styles.rowPressed]}><Image source={ancestor.image} style={[styles.simpleAncestorImage, ancestor.missing && styles.ancestorImageMissing]} contentFit="cover" cachePolicy="memory-disk" /><View style={styles.simpleAncestorCopy}><Text style={styles.simpleAncestorBranch}>{branch} - {ancestor.relation}</Text><Text numberOfLines={1} style={styles.simpleAncestorName}>{ancestor.name}</Text><Text numberOfLines={1} style={styles.simpleAncestorMeta}>{ancestor.bloodline} - {ancestor.id}</Text></View><Ionicons name="chevron-forward" size={17} color="#849095" /></Pressable>;
}

function AncestorCard({ bird, compact, branch }) {
  return <Pressable onPress={() => bird.missing ? Alert.alert('Ancestor not recorded', 'Add this ancestor to complete the pedigree.') : Alert.alert(bird.name, `${bird.bloodline}\n${bird.id}`)} style={({ pressed }) => [styles.ancestorCard, compact && styles.ancestorCardCompact, branch && styles.ancestorBranchCard, !branch && styles.parentAncestorCard, pressed && styles.cardPressed]}><View style={styles.ancestorImageWrap}><Image source={bird.image} style={[styles.ancestorImage, !branch && styles.parentAncestorImage, bird.missing && styles.ancestorImageMissing]} contentFit="cover" cachePolicy="memory-disk" /><View style={styles.genderBadge}><MaterialCommunityIcons name={bird.gender === 'male' ? 'gender-male' : 'gender-female'} size={14} color={ORANGE} /></View></View><View style={[styles.ancestorCopy, !branch && styles.parentAncestorCopy]}><Text style={[styles.ancestorRelation, !branch && styles.parentAncestorText]}>{bird.relation}</Text><Text numberOfLines={1} style={[styles.ancestorName, !branch && styles.parentAncestorText]}>{bird.name}</Text><Text numberOfLines={1} style={[styles.ancestorBloodline, !branch && styles.parentAncestorText]}>{bird.bloodline}</Text><Text numberOfLines={1} style={[styles.ancestorId, !branch && styles.parentAncestorText]}>{bird.id}</Text></View><View style={!branch && styles.parentAncestorChevron}><Ionicons name="chevron-forward" size={18} color="#899397" /></View></Pressable>;
}

function LineageSection({ title, parent, grandparents, compact }) {
  return <View style={styles.lineageSection}><View style={styles.lineageHeading}><View style={styles.lineageHeadingIcon}><MaterialCommunityIcons name={parent.gender === 'male' ? 'gender-male' : 'gender-female'} size={18} color={ORANGE} /></View><View><Text style={styles.lineageTitle}>{title}</Text><Text style={styles.lineageSubtitle}>Parent and grandparent records</Text></View></View><AncestorCard bird={parent} compact={compact} /><View style={styles.branch}><View style={styles.branchStem} /><View style={styles.branchBar} /></View><View style={styles.grandparents}>{grandparents.map((bird) => <AncestorCard key={`${bird.relation}-${bird.name}`} bird={bird} compact branch />)}</View></View>;
}

function CompositionBar({ item }) {
  return <View style={styles.compositionRow}><View style={styles.compositionHeading}><Text style={styles.compositionLabel}>{item.label}</Text><Text style={styles.compositionValue}>{item.value}%</Text></View><View style={styles.compositionTrack}><View style={[styles.compositionFill, { width: `${item.value}%` }]} /></View></View>;
}

function DocumentRow({ icon, title, detail, status, isLast, onPress }) {
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.documentRow, !isLast && styles.rowDivider, pressed && styles.rowPressed]}><View style={styles.documentIcon}><MaterialCommunityIcons name={icon} size={21} color={ORANGE} /></View><View style={styles.documentCopy}><Text style={styles.documentTitle}>{title}</Text><Text style={styles.documentDetail}>{detail}</Text></View><View style={styles.documentStatus}><Text style={styles.documentStatusText}>{status}</Text></View><Ionicons name="chevron-forward" size={18} color="#899397" /></Pressable>;
}

export default function PedigreeBloodlineScreen({ bird, onBack }) {
  const { width } = useWindowDimensions(); const compact = width < 520; const narrow = width < 390;
  if (!bird) return <View style={styles.missingScreen}><Text style={styles.missingTitle}>Bird record unavailable</Text><Pressable onPress={onBack} style={styles.missingButton}><Text style={styles.missingButtonText}>Back to Bird Profile</Text></Pressable></View>;
  const pedigree = bird.name === 'Razor 014' ? RAZOR_PEDIGREE : makeFallbackPedigree(bird);
  const knownAncestors = [pedigree.sire, pedigree.dam, ...pedigree.paternal, ...pedigree.maternal].filter((item) => !item.missing).length;
  return <View style={styles.screen}><StatusBar style="light" translucent backgroundColor="transparent" /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.pageWrap}><View style={styles.page}><View style={[styles.hero, compact && styles.heroCompact]}><Image source={FLOCK_HERO_IMAGE} style={StyleSheet.absoluteFill} contentFit="cover" contentPosition="center" cachePolicy="memory-disk" /><LinearGradient colors={['rgba(2,7,9,0.2)', 'rgba(2,7,9,0.18)', 'rgba(2,7,9,0.86)', '#03090c']} locations={[0, 0.38, 0.76, 1]} style={StyleSheet.absoluteFill} /><SafeAreaView edges={['top']} style={styles.heroSafeArea}><View style={styles.heroHeader}><View style={styles.heroHeaderLeft}><HeaderButton icon="arrow-back" label="Back to bird profile" onPress={onBack} /><Text style={styles.screenTitle}>Pedigree & Bloodline</Text></View></View><View style={[styles.heroCopy, narrow && styles.heroCopyNarrow]}><View style={[styles.heroPortrait, narrow && styles.heroPortraitNarrow]}><Image source={bird.image} style={StyleSheet.absoluteFill} contentFit="cover" contentPosition="center" cachePolicy="memory-disk" /></View><View style={styles.heroIdentity}><Text numberOfLines={1} style={[styles.birdName, narrow && styles.birdNameNarrow]}>{bird.name}</Text><View style={styles.heroMetaRow}><View style={styles.bloodlineBadge}><MaterialCommunityIcons name="dna" size={14} color={ORANGE} /><Text numberOfLines={1} style={styles.bloodlineBadgeText}>{bird.bloodline}</Text></View><View style={styles.typeMeta}><MaterialCommunityIcons name={bird.filter === 'hen' || bird.filter === 'pullet' ? 'gender-female' : 'gender-male'} size={14} color={ORANGE} /><Text style={styles.typeMetaText}>{bird.type}</Text></View></View></View></View></SafeAreaView></View>
    <View style={[styles.content, narrow && styles.contentNarrow]}>
      <Pressable accessibilityRole="button" accessibilityLabel={`QR code for ${getFarmBuzzId(bird)}`} onPress={() => Alert.alert('FarmBuzz ID', getFarmBuzzId(bird))} style={({ pressed }) => [styles.simpleIdRow, pressed && styles.cardPressed]}><View style={styles.simpleIdIcon}><MaterialCommunityIcons name="qrcode" size={22} color={ORANGE} /></View><View style={styles.simpleIdCopy}><Text style={styles.simpleIdLabel}>FARMBUZZ ID</Text><Text style={styles.simpleIdValue}>{getFarmBuzzId(bird)}</Text></View><Image source={getQrCodeUrl(getFarmBuzzId(bird))} style={styles.simpleQr} contentFit="contain" cachePolicy="memory-disk" /></Pressable>
      <Text style={styles.restoredLineageTitle}>Family Lineage</Text>
      <View style={[styles.lineageGrid, compact && styles.lineageGridCompact]}><LineageSection title="Paternal Line" parent={pedigree.sire} grandparents={pedigree.paternal} compact={compact} /><LineageSection title="Maternal Line" parent={pedigree.dam} grandparents={pedigree.maternal} compact={compact} /></View>
      <View style={styles.simpleSectionHeading}><View><Text style={styles.sectionTitle}>Bloodline Mix</Text><Text style={styles.simpleSectionSubtitle}>Based on recorded family</Text></View></View>
      <View style={styles.mixPanel}>{pedigree.composition.map((item) => <View key={item.label} style={styles.mixItem}><Text style={styles.mixValue}>{item.value}%</Text><Text numberOfLines={1} style={styles.mixLabel}>{item.label}</Text></View>)}</View>
      <Pressable accessibilityRole="button" accessibilityLabel="Edit pedigree" onPress={() => Alert.alert('Edit pedigree', `Edit the pedigree for ${bird.name}.`)} style={({ pressed }) => [styles.pedigreeAction, pressed && styles.cardPressed]}><View style={styles.pedigreeActionIcon}><MaterialCommunityIcons name="family-tree" size={22} color={ORANGE} /></View><View style={styles.pedigreeActionCopy}><Text style={styles.pedigreeActionTitle}>{knownAncestors ? 'Edit Pedigree' : 'Add Parents'}</Text><Text style={styles.pedigreeActionText}>{knownAncestors ? 'Update parents and family records' : 'Start this bird\'s family lineage'}</Text></View><View style={styles.pedigreeActionArrow}><Ionicons name="arrow-forward" size={17} color="#fff" /></View></Pressable>
    </View></View></ScrollView></View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#020709' }, pageWrap: { flexGrow: 1, alignItems: 'center', backgroundColor: '#020709' }, page: { width: '100%', maxWidth: 720, backgroundColor: '#020709' }, hero: { height: 285, overflow: 'hidden' }, heroCompact: { height: 265 }, heroSafeArea: { flex: 1 }, heroHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingTop: Platform.OS === 'web' ? 10 : 3 }, heroHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 }, headerButton: { width: 40, height: 40, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(190,204,208,0.35)', backgroundColor: 'rgba(2,8,11,0.65)', alignItems: 'center', justifyContent: 'center' }, screenTitle: { color: '#f1f3f3', fontSize: 17, fontWeight: '700' },
  heroCopy: { marginTop: 'auto', paddingHorizontal: 18, paddingBottom: 20, flexDirection: 'row', alignItems: 'flex-end', gap: 13 }, heroCopyNarrow: { paddingHorizontal: 11, paddingBottom: 16, gap: 10 },
  heroPortrait: { width: 78, height: 78, borderRadius: 8, borderWidth: 2, borderColor: ORANGE, overflow: 'hidden', backgroundColor: '#11191c', shadowColor: '#000', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.45, shadowRadius: 8, elevation: 7 }, heroPortraitNarrow: { width: 68, height: 68, borderRadius: 7 },
  heroIdentity: { flex: 1, minWidth: 0, paddingBottom: 2 },
  heroMetaRow: { marginTop: 6, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  bloodlineBadge: { alignSelf: 'flex-start', maxWidth: '70%', height: 26, paddingHorizontal: 8, borderWidth: 1, borderColor: '#67410f', borderRadius: 13, backgroundColor: 'rgba(8,12,10,0.7)', flexDirection: 'row', alignItems: 'center', gap: 5 }, bloodlineBadgeText: { flexShrink: 1, color: '#e1a35a', fontSize: 8, fontWeight: '700' },
  typeMeta: { height: 26, flexDirection: 'row', alignItems: 'center', gap: 4 }, typeMetaText: { color: '#d5dbdc', fontSize: 9, fontWeight: '600' },
  birdName: { color: '#f2f4f4', fontSize: 29, lineHeight: 34, fontWeight: '800', textShadowColor: 'rgba(0,0,0,0.75)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 5 }, birdNameNarrow: { fontSize: 24, lineHeight: 29 }, farmBuzzId: { marginTop: 5, color: '#a2acae', fontSize: 10 },
  content: { paddingHorizontal: 14, paddingTop: 14, paddingBottom: 30 }, contentNarrow: { paddingHorizontal: 9 }, summaryPanel: { minHeight: 104, paddingVertical: 12, borderWidth: 1, borderColor: '#28353a', borderRadius: 8, backgroundColor: '#0a1317', flexDirection: 'row', alignItems: 'stretch' }, summaryItem: { flex: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 5 }, summaryDivider: { width: 1, backgroundColor: '#26343a' }, summaryValue: { marginTop: 5, color: '#eef1f2', fontSize: 13, fontWeight: '800', textAlign: 'center' }, summaryLabel: { marginTop: 3, color: '#7e898d', fontSize: 8, textAlign: 'center' }, currentBirdPanel: { minHeight: 104, marginTop: 10, marginBottom: 18, padding: 11, borderWidth: 1, borderColor: '#5b3b14', borderRadius: 8, backgroundColor: 'rgba(255,122,0,0.045)', flexDirection: 'row', alignItems: 'center', gap: 10 }, currentBirdImage: { width: 66, height: 66, borderRadius: 33, borderWidth: 2, borderColor: ORANGE }, currentBirdCopy: { flex: 1, minWidth: 0 }, currentEyebrow: { color: ORANGE, fontSize: 7, fontWeight: '800' }, currentBirdName: { marginTop: 4, color: '#edf0f1', fontSize: 14, fontWeight: '800' }, currentBirdBloodline: { marginTop: 3, color: '#939ea1', fontSize: 9 }, currentIdBadge: { alignSelf: 'flex-start', marginTop: 6, paddingHorizontal: 7, paddingVertical: 4, borderWidth: 1, borderColor: '#69410e', borderRadius: 5 }, currentIdText: { color: ORANGE, fontSize: 8, fontWeight: '700' }, qrButton: { width: 72, flexShrink: 0, alignItems: 'center' }, qrImage: { width: 66, height: 66, borderRadius: 4, backgroundColor: '#fff' }, qrLabel: { marginTop: 4, color: '#a8b1b4', fontSize: 7, fontWeight: '700' }, sectionTitle: { marginTop: 4, marginBottom: 8, color: '#e7eaeb', fontSize: 14, fontWeight: '700' },
  simpleIdRow: { minHeight: 68, padding: 9, borderWidth: 1, borderColor: '#583a14', borderRadius: 8, backgroundColor: 'rgba(255,122,0,0.045)', flexDirection: 'row', alignItems: 'center', gap: 10 },
  simpleIdIcon: { width: 40, height: 40, borderRadius: 7, backgroundColor: 'rgba(255,122,0,0.08)', alignItems: 'center', justifyContent: 'center' },
  simpleIdCopy: { flex: 1, minWidth: 0 }, simpleIdLabel: { color: '#7e898d', fontSize: 7, fontWeight: '700' }, simpleIdValue: { marginTop: 4, color: '#edf0f1', fontSize: 12, fontWeight: '800' }, simpleQr: { width: 46, height: 46, borderRadius: 4, backgroundColor: '#fff' },
  restoredLineageTitle: { marginTop: 18, marginBottom: 8, color: '#e7eaeb', fontSize: 14, fontWeight: '700' },
  pedigreeAction: { minHeight: 68, marginTop: 14, paddingHorizontal: 10, borderWidth: 1, borderColor: '#62400f', borderRadius: 8, backgroundColor: 'rgba(255,122,0,0.055)', flexDirection: 'row', alignItems: 'center', gap: 10 },
  pedigreeActionIcon: { width: 42, height: 42, borderRadius: 7, backgroundColor: 'rgba(255,122,0,0.1)', alignItems: 'center', justifyContent: 'center' },
  pedigreeActionCopy: { flex: 1, minWidth: 0 }, pedigreeActionTitle: { color: '#edf0f1', fontSize: 11, fontWeight: '800' }, pedigreeActionText: { marginTop: 4, color: '#849095', fontSize: 8 },
  pedigreeActionArrow: { width: 32, height: 32, borderRadius: 16, backgroundColor: ORANGE, alignItems: 'center', justifyContent: 'center' },
  simpleSectionHeading: { minHeight: 58, paddingTop: 12, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' }, simpleSectionSubtitle: { marginTop: -5, marginBottom: 8, color: '#748084', fontSize: 8 }, simpleCount: { marginBottom: 8, color: ORANGE, fontSize: 8, fontWeight: '700' },
  parentsGrid: { flexDirection: 'row', gap: 8 },
  simpleParent: { flex: 1, minWidth: 0, minHeight: 138, padding: 10, borderWidth: 1, borderColor: '#28353a', borderRadius: 8, backgroundColor: '#0a1317', alignItems: 'center', justifyContent: 'center' },
  simpleParentImage: { width: 58, height: 58, borderRadius: 29, borderWidth: 1, borderColor: '#65400e' }, simpleRelation: { marginTop: 8, color: ORANGE, fontSize: 7, fontWeight: '800', textTransform: 'uppercase' }, simpleParentName: { maxWidth: '100%', marginTop: 4, color: '#e6eaeb', fontSize: 11, fontWeight: '700' }, simpleParentBloodline: { maxWidth: '100%', marginTop: 3, color: '#7f8b8f', fontSize: 8 },
  grandparentsTrigger: { minHeight: 62, marginTop: 9, paddingHorizontal: 10, borderWidth: 1, borderColor: '#28353a', borderRadius: 8, backgroundColor: '#0a1317', flexDirection: 'row', alignItems: 'center', gap: 9 }, grandparentsTriggerIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(255,122,0,0.08)', alignItems: 'center', justifyContent: 'center' }, grandparentsTriggerTitle: { color: '#dfe3e4', fontSize: 10, fontWeight: '700' }, grandparentsTriggerText: { marginTop: 3, color: '#778488', fontSize: 8 },
  simpleAncestorsPanel: { marginTop: 7, borderWidth: 1, borderColor: '#28353a', borderRadius: 8, backgroundColor: '#0a1317', overflow: 'hidden' }, simpleAncestorRow: { minHeight: 64, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 9 }, simpleAncestorImage: { width: 40, height: 40, borderRadius: 20, borderWidth: 1, borderColor: '#5d3c12' }, simpleAncestorCopy: { flex: 1, minWidth: 0 }, simpleAncestorBranch: { color: ORANGE, fontSize: 7, fontWeight: '700', textTransform: 'uppercase' }, simpleAncestorName: { marginTop: 3, color: '#dfe3e4', fontSize: 10, fontWeight: '700' }, simpleAncestorMeta: { marginTop: 2, color: '#758185', fontSize: 7 },
  mixPanel: { minHeight: 76, padding: 10, borderWidth: 1, borderColor: '#28353a', borderRadius: 8, backgroundColor: '#0a1317', flexDirection: 'row', alignItems: 'stretch' }, mixItem: { flex: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', borderRightWidth: 1, borderRightColor: '#223037' }, mixValue: { color: ORANGE, fontSize: 15, fontWeight: '800' }, mixLabel: { maxWidth: '100%', marginTop: 4, color: '#929da0', fontSize: 8 },
  lineageGrid: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginBottom: 18 }, lineageGridCompact: { flexDirection: 'column' }, lineageSection: { flex: 1, width: '100%', minWidth: 0, padding: 10, borderWidth: 1, borderColor: '#28353a', borderRadius: 8, backgroundColor: '#081115' }, lineageHeading: { minHeight: 43, flexDirection: 'row', alignItems: 'center', gap: 8 }, lineageHeadingIcon: { width: 34, height: 34, borderRadius: 17, backgroundColor: 'rgba(255,122,0,0.08)', alignItems: 'center', justifyContent: 'center' }, lineageTitle: { color: '#e5e9ea', fontSize: 11, fontWeight: '700' }, lineageSubtitle: { marginTop: 2, color: '#748084', fontSize: 7 }, ancestorCard: { minHeight: 75, padding: 8, borderWidth: 1, borderColor: '#26343a', borderRadius: 7, backgroundColor: '#0a1317', flexDirection: 'row', alignItems: 'center', gap: 8 }, ancestorCardCompact: { minHeight: 68 }, ancestorBranchCard: { flex: 1, minWidth: 0 }, parentAncestorCard: { minHeight: 92, flexDirection: 'row', justifyContent: 'center', paddingHorizontal: 30 }, ancestorImageWrap: { position: 'relative' }, ancestorImage: { width: 48, height: 48, borderRadius: 24, borderWidth: 1, borderColor: '#68430f' }, parentAncestorImage: { width: 56, height: 56, borderRadius: 28, borderWidth: 2, borderColor: ORANGE }, ancestorImageMissing: { opacity: 0.3 }, genderBadge: { position: 'absolute', right: -2, top: -2, width: 20, height: 20, borderRadius: 10, borderWidth: 1, borderColor: '#573810', backgroundColor: '#11191b', alignItems: 'center', justifyContent: 'center' }, ancestorCopy: { flex: 1, minWidth: 0 }, parentAncestorCopy: { flex: 0, width: '48%', minWidth: 86, maxWidth: 150, alignItems: 'flex-start', justifyContent: 'center' }, parentAncestorText: { width: '100%', textAlign: 'left' }, parentAncestorChevron: { position: 'absolute', right: 8, top: '50%', marginTop: -9 }, ancestorRelation: { color: ORANGE, fontSize: 7, fontWeight: '800', textTransform: 'uppercase' }, ancestorName: { marginTop: 3, color: '#e1e5e6', fontSize: 10, fontWeight: '700' }, ancestorBloodline: { marginTop: 2, color: '#889397', fontSize: 8 }, ancestorId: { marginTop: 2, color: '#687478', fontSize: 7 }, branch: { height: 22, alignItems: 'center' }, branchStem: { height: 11, width: 1, backgroundColor: '#68410e' }, branchBar: { width: '52%', height: 1, backgroundColor: '#68410e' }, grandparents: { flexDirection: 'row', alignItems: 'stretch', gap: 7 },
  compositionPanel: { marginBottom: 18, padding: 12, borderWidth: 1, borderColor: '#28353a', borderRadius: 8, backgroundColor: '#0a1317' }, compositionRow: { marginBottom: 11 }, compositionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, compositionLabel: { color: '#dce1e2', fontSize: 10, fontWeight: '600' }, compositionValue: { color: ORANGE, fontSize: 10, fontWeight: '800' }, compositionTrack: { height: 7, marginTop: 6, borderRadius: 4, backgroundColor: '#1b292f', overflow: 'hidden' }, compositionFill: { height: '100%', borderRadius: 4, backgroundColor: ORANGE }, compositionNote: { minHeight: 37, marginTop: 2, paddingHorizontal: 9, borderRadius: 7, backgroundColor: 'rgba(255,122,0,0.05)', flexDirection: 'row', alignItems: 'center', gap: 7 }, compositionNoteText: { flex: 1, color: '#899397', fontSize: 8 }, documentsPanel: { marginBottom: 14, borderWidth: 1, borderColor: '#28353a', borderRadius: 8, backgroundColor: '#0a1317', overflow: 'hidden' }, documentRow: { minHeight: 65, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 9 }, rowDivider: { borderBottomWidth: 1, borderBottomColor: '#223037' }, rowPressed: { backgroundColor: '#111d22' }, documentIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(255,122,0,0.07)', alignItems: 'center', justifyContent: 'center' }, documentCopy: { flex: 1, minWidth: 0 }, documentTitle: { color: '#dfe3e4', fontSize: 10, fontWeight: '700' }, documentDetail: { marginTop: 3, color: '#758185', fontSize: 8 }, documentStatus: { paddingHorizontal: 7, paddingVertical: 4, borderWidth: 1, borderColor: '#69410e', borderRadius: 10 }, documentStatusText: { color: ORANGE, fontSize: 7, fontWeight: '700' }, actions: { flexDirection: 'row', gap: 8 }, secondaryButton: { flex: 0.9, height: 50, borderWidth: 1, borderColor: '#68400e', borderRadius: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, secondaryText: { color: ORANGE, fontSize: 10, fontWeight: '700' }, primaryButton: { flex: 1.1, height: 50, borderRadius: 8, backgroundColor: '#f66f00', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, fullButton: { flex: 0, width: '100%', marginTop: 14 }, primaryText: { color: '#fff', fontSize: 10, fontWeight: '700' }, pressed: { opacity: 0.72 }, cardPressed: { opacity: 0.76, transform: [{ scale: 0.995 }] }, missingScreen: { flex: 1, backgroundColor: '#020709', alignItems: 'center', justifyContent: 'center' }, missingTitle: { color: '#d8ddde', fontSize: 17, fontWeight: '700' }, missingButton: { height: 44, marginTop: 18, paddingHorizontal: 18, borderRadius: 8, backgroundColor: '#f66f00', alignItems: 'center', justifyContent: 'center' }, missingButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
});
