import { Alert, Platform, Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { DEFAULT_MEMBER_ACCESS } from './EditMemberAccessScreen';

const ORANGE = '#ff7a00';

function HeaderButton({ icon, label, onPress }) {
  return <Pressable accessibilityLabel={label} onPress={onPress} style={({ pressed }) => [styles.headerButton, pressed && styles.pressed]}><Ionicons name={icon} size={21} color="#eef1f2" /></Pressable>;
}

function Fact({ icon, value, label, isLast }) {
  return <View style={[styles.fact, !isLast && styles.factDivider]}><MaterialCommunityIcons name={icon} size={20} color={ORANGE} /><Text numberOfLines={1} style={styles.factValue}>{value}</Text><Text numberOfLines={1} style={styles.factLabel}>{label}</Text></View>;
}

function AccessRow({ module, level, isLast }) {
  const icon = module === 'Flock' ? 'bird' : module === 'Breeding' ? 'gender-male-female' : module === 'Health & Care' ? 'shield-cross-outline' : module === 'Eggs & Incubation' ? 'egg-outline' : module === 'Tasks' ? 'clipboard-check-outline' : 'account-group-outline';
  return <View style={[styles.accessRow, !isLast && styles.divider]}><View style={styles.accessIcon}><MaterialCommunityIcons name={icon} size={19} color={ORANGE} /></View><View style={styles.accessCopy}><Text style={styles.accessModule}>{module}</Text><Text style={styles.accessDescription}>{level === 'Manage' ? 'Can create and update records' : level === 'View' ? 'Can view records only' : 'No access to this module'}</Text></View><View style={[styles.accessBadge, level === 'None' && styles.accessBadgeMuted]}><Text style={[styles.accessLevel, level === 'None' && styles.accessLevelMuted]}>{level}</Text></View></View>;
}

export default function TeamMemberDetailScreen({ member, onBack, onEditAccess }) {
  const { width } = useWindowDimensions();
  const compact = width < 480;
  const narrow = width < 380;
  if (!member) return null;

  const access = { ...(DEFAULT_MEMBER_ACCESS[member.role] || DEFAULT_MEMBER_ACCESS['Farm Assistant']), ...member.permissions };
  const accessEntries = Object.entries(access);
  const manageable = accessEntries.filter(([, level]) => level === 'Manage').length;

  return (
    <View style={styles.screen}><StatusBar style="light" translucent backgroundColor="transparent" /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.pageWrap}><View style={styles.page}>
      <View style={[styles.hero, compact && styles.heroCompact]}><Image source={member.image} style={StyleSheet.absoluteFill} contentFit="cover" contentPosition="center" cachePolicy="memory-disk" /><LinearGradient colors={['rgba(2,7,9,0.1)', 'rgba(2,7,9,0.32)', '#03090c']} locations={[0, 0.48, 1]} style={StyleSheet.absoluteFill} /><SafeAreaView edges={['top']} style={styles.heroSafeArea}><View style={styles.heroHeader}><View style={styles.heroHeaderLeft}><HeaderButton icon="arrow-back" label="Back to team" onPress={onBack} /><Text style={styles.screenTitle}>Team Member</Text></View><HeaderButton icon="ellipsis-horizontal" label="Member options" onPress={() => Alert.alert('Member options', `Manage ${member.name}'s team record.`)} /></View><View style={[styles.heroCopy, narrow && styles.heroCopyNarrow]}><Text style={styles.memberId}>MEM-{member.id.toUpperCase().replace(/[^A-Z0-9]/g, '-')}</Text><Text numberOfLines={1} style={[styles.memberName, narrow && styles.memberNameNarrow]}>{member.name}</Text><Text style={styles.memberRole}>{member.role}</Text><View style={styles.statusRow}><View style={styles.statusDot} /><Text style={styles.statusText}>{member.status}</Text></View></View></SafeAreaView></View>
      <View style={[styles.content, narrow && styles.contentNarrow]}>
        <View style={styles.facts}><Fact icon="barn" value={member.farm || member.team} label={member.farmIds?.length > 1 ? 'Farm Access' : 'Assigned Farm'} /><Fact icon="clock-outline" value={member.shift} label="Schedule" /><Fact icon="clipboard-check-outline" value={member.tasks} label="Assignments" isLast /></View>

        <View style={styles.contactPanel}><Pressable onPress={() => Alert.alert('Call', `Call ${member.name}`)} style={({ pressed }) => [styles.contactButton, pressed && styles.pressed]}><Ionicons name="call-outline" size={19} color={ORANGE} /><Text style={styles.contactText}>Call</Text></Pressable><Pressable onPress={() => Alert.alert('Message', `Message ${member.name}`)} style={({ pressed }) => [styles.contactButton, pressed && styles.pressed]}><Ionicons name="chatbubble-outline" size={19} color={ORANGE} /><Text style={styles.contactText}>Message</Text></Pressable><Pressable onPress={() => Alert.alert('Email', `${member.id}@farmbuzz.local`)} style={({ pressed }) => [styles.contactButton, pressed && styles.pressed]}><Ionicons name="mail-outline" size={19} color={ORANGE} /><Text style={styles.contactText}>Email</Text></Pressable></View>

        <View style={styles.sectionHeading}><View><Text style={styles.sectionTitle}>Role & Permissions</Text><Text style={styles.sectionSubtitle}>{manageable} modules with management access</Text></View><Pressable accessibilityLabel="Edit role and permissions" onPress={onEditAccess} style={styles.editButton}><MaterialCommunityIcons name="pencil-outline" size={15} color={ORANGE} /><Text style={styles.editText}>Edit</Text></Pressable></View>
        <View style={styles.accessPanel}>{accessEntries.map(([module, level], index) => <AccessRow key={module} module={module} level={level} isLast={index === accessEntries.length - 1} />)}</View>

        <View style={styles.sectionHeading}><View><Text style={styles.sectionTitle}>Current Assignments</Text><Text style={styles.sectionSubtitle}>Work assigned for today</Text></View><Text style={styles.sectionCount}>3 active</Text></View>
        <View style={styles.assignmentPanel}>{['Morning flock health check', 'Review assigned farm tasks', 'Submit end-of-shift update'].map((title, index) => <View key={title} style={[styles.assignmentRow, index < 2 && styles.divider]}><View style={styles.assignmentIcon}><MaterialCommunityIcons name={index === 0 ? 'shield-check-outline' : index === 1 ? 'clipboard-check-outline' : 'text-box-check-outline'} size={19} color={ORANGE} /></View><View style={styles.assignmentCopy}><Text style={styles.assignmentTitle}>{title}</Text><Text style={styles.assignmentMeta}>{index === 0 ? 'Due 9:00 AM' : index === 1 ? member.tasks : 'Due before clock-out'}</Text></View><View style={styles.assignmentDot} /></View>)}</View>

        <Pressable onPress={onEditAccess} style={({ pressed }) => [styles.primaryButton, pressed && styles.pressed]}><MaterialCommunityIcons name="account-lock-outline" size={20} color="#fff" /><Text style={styles.primaryText}>Edit Role & Permissions</Text></Pressable>
      </View>
    </View></ScrollView></View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#020709' }, pageWrap: { flexGrow: 1, alignItems: 'center', backgroundColor: '#020709' }, page: { width: '100%', maxWidth: 720, backgroundColor: '#020709' }, hero: { height: 330, overflow: 'hidden', backgroundColor: '#101719' }, heroCompact: { height: 300 }, heroSafeArea: { flex: 1 }, heroHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingTop: Platform.OS === 'web' ? 10 : 3 }, heroHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 }, headerButton: { width: 40, height: 40, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(190,204,208,0.35)', backgroundColor: 'rgba(2,8,11,0.65)', alignItems: 'center', justifyContent: 'center' }, screenTitle: { color: '#f1f3f3', fontSize: 17, fontWeight: '700' }, heroCopy: { marginTop: 'auto', paddingHorizontal: 18, paddingBottom: 26 }, heroCopyNarrow: { paddingHorizontal: 11, paddingBottom: 20 }, memberId: { color: ORANGE, fontSize: 8, fontWeight: '800' }, memberName: { marginTop: 5, color: '#f4f5f5', fontSize: 32, lineHeight: 38, fontWeight: '800' }, memberNameNarrow: { fontSize: 27, lineHeight: 32 }, memberRole: { marginTop: 4, color: '#c0c8ca', fontSize: 12 }, statusRow: { alignSelf: 'flex-start', minHeight: 27, marginTop: 10, paddingHorizontal: 9, borderWidth: 1, borderColor: '#68430f', borderRadius: 14, backgroundColor: 'rgba(255,122,0,0.08)', flexDirection: 'row', alignItems: 'center', gap: 6 }, statusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: ORANGE }, statusText: { color: '#e3a057', fontSize: 8, fontWeight: '700' },
  content: { paddingHorizontal: 12, paddingTop: 10, paddingBottom: 30 }, contentNarrow: { paddingHorizontal: 8 }, facts: { minHeight: 94, borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317', flexDirection: 'row', overflow: 'hidden' }, fact: { flex: 1, minWidth: 0, padding: 8, alignItems: 'center', justifyContent: 'center' }, factDivider: { borderRightWidth: 1, borderRightColor: '#223037' }, factValue: { maxWidth: '100%', marginTop: 5, color: '#edf0f1', fontSize: 10, fontWeight: '800', textAlign: 'center' }, factLabel: { marginTop: 4, color: '#7e8a8e', fontSize: 7 }, contactPanel: { minHeight: 58, marginTop: 9, borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317', flexDirection: 'row' }, contactButton: { flex: 1, borderRightWidth: 1, borderRightColor: '#223037', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, contactText: { color: '#b5bec0', fontSize: 9, fontWeight: '700' },
  sectionHeading: { minHeight: 60, paddingTop: 19, paddingBottom: 8, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 10 }, sectionTitle: { color: '#e7eaeb', fontSize: 15, fontWeight: '700' }, sectionSubtitle: { marginTop: 3, color: '#737f83', fontSize: 8 }, sectionCount: { color: ORANGE, fontSize: 8, fontWeight: '700' }, editButton: { height: 30, paddingHorizontal: 10, borderWidth: 1, borderColor: '#62400f', borderRadius: 15, flexDirection: 'row', alignItems: 'center', gap: 5 }, editText: { color: ORANGE, fontSize: 8, fontWeight: '700' }, accessPanel: { borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317', overflow: 'hidden' }, accessRow: { minHeight: 66, padding: 9, flexDirection: 'row', alignItems: 'center', gap: 9 }, divider: { borderBottomWidth: 1, borderBottomColor: '#223037' }, accessIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(255,122,0,0.08)', alignItems: 'center', justifyContent: 'center' }, accessCopy: { flex: 1, minWidth: 0 }, accessModule: { color: '#dfe3e4', fontSize: 10, fontWeight: '700' }, accessDescription: { marginTop: 3, color: '#788488', fontSize: 7 }, accessBadge: { minWidth: 52, height: 25, paddingHorizontal: 7, borderWidth: 1, borderColor: '#64410f', borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, accessBadgeMuted: { borderColor: '#354248' }, accessLevel: { color: ORANGE, fontSize: 7, fontWeight: '800' }, accessLevelMuted: { color: '#788488' },
  assignmentPanel: { borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317', overflow: 'hidden' }, assignmentRow: { minHeight: 64, padding: 9, flexDirection: 'row', alignItems: 'center', gap: 9 }, assignmentIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(255,122,0,0.08)', alignItems: 'center', justifyContent: 'center' }, assignmentCopy: { flex: 1 }, assignmentTitle: { color: '#dfe3e4', fontSize: 10, fontWeight: '700' }, assignmentMeta: { marginTop: 4, color: '#788488', fontSize: 8 }, assignmentDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: ORANGE }, primaryButton: { height: 52, marginTop: 14, borderRadius: 8, backgroundColor: '#f66f00', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, primaryText: { color: '#fff', fontSize: 12, fontWeight: '800' }, pressed: { opacity: 0.72 },
});
