import { useMemo, useState } from 'react';
import { Alert, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';

const HEALTH_HERO_IMAGE = require('./assets/health-care-hero.png');
const ORANGE = '#ff7a00';
const ROOSTER_IMAGE = 'https://images.unsplash.com/photo-1730360037813-9777f13b88bb?auto=format&fit=crop&w=300&q=82';
const BLACK_ROOSTER_IMAGE = 'https://images.unsplash.com/photo-1551127501-d4385c7484b4?auto=format&fit=crop&w=300&q=82';
const HEN_IMAGE = 'https://images.unsplash.com/photo-1770221499235-11dd1041e181?auto=format&fit=crop&w=300&q=82';
const BROWN_HEN_IMAGE = 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&w=300&q=82';

export const DEFAULT_VACCINATIONS = [
  { id: 'vac-001', name: 'Cock FB-00142', breed: 'Bloodline unknown', image: ROOSTER_IMAGE, vaccine: 'Newcastle Booster', dose: '0.5 mL', method: 'Subcutaneous', dueDate: 'Aug 29, 2026', status: 'Overdue' },
  { id: 'vac-002', name: 'Lady 052', breed: 'Roundhead Hen', image: HEN_IMAGE, vaccine: 'Fowl Pox', dose: 'Wing web dose', method: 'Wing web', dueDate: 'Sep 1, 2026', status: 'Due' },
  { id: 'vac-003', name: 'Razor 014', breed: 'Kelso Cock', image: ROOSTER_IMAGE, vaccine: 'Newcastle Booster', dose: '0.5 mL', method: 'Subcutaneous', dueDate: 'Sep 5, 2026', status: 'Upcoming' },
  { id: 'vac-004', name: 'Ruby 052', breed: 'Roundhead Pullet', image: BROWN_HEN_IMAGE, vaccine: 'Infectious Bronchitis', dose: '1 drop', method: 'Eye drop', dueDate: 'Sep 12, 2026', status: 'Upcoming' },
  { id: 'vac-005', name: 'Blade 008', breed: 'Hatch Cock', image: BLACK_ROOSTER_IMAGE, vaccine: 'Newcastle Booster', dose: '0.5 mL', method: 'Subcutaneous', dueDate: 'Aug 28, 2026', administeredDate: 'Aug 28, 2026', administeredBy: 'Maria Santos', batchNumber: 'ND-2608-B4', status: 'Completed' },
];

const FILTERS = ['All', 'Due', 'Upcoming', 'Completed'];

function HeaderButton({ icon, label, onPress }) { return <Pressable accessibilityLabel={label} onPress={onPress} style={({ pressed }) => [styles.headerButton, pressed && styles.pressed]}><Ionicons name={icon} size={21} color="#eef1f2" /></Pressable>; }

function SummaryCard({ icon, value, label, isLast }) { return <View style={[styles.summaryCard, !isLast && styles.summaryDivider]}><View style={styles.summaryIcon}><MaterialCommunityIcons name={icon} size={23} color={ORANGE} /></View><Text style={styles.summaryValue}>{value}</Text><Text numberOfLines={2} style={styles.summaryLabel}>{label}</Text></View>; }

function VaccinationRow({ item, compact, onMarkGiven, onOpen }) {
  const actionable = item.status !== 'Completed';
  return (
    <Pressable onPress={() => onOpen(item)} style={({ pressed }) => [styles.vaccineCard, pressed && styles.cardPressed]}>
      <View style={styles.vaccineTop}><Image source={item.image} style={styles.birdImage} contentFit="cover" cachePolicy="memory-disk" /><View style={styles.vaccineCopy}><View style={styles.nameRow}><Text numberOfLines={1} style={styles.birdName}>{item.name}</Text><View style={[styles.statusBadge, item.status === 'Completed' && styles.statusCompleted]}><Text style={styles.statusText}>{item.status}</Text></View></View><Text style={styles.birdBreed}>{item.breed}</Text><Text numberOfLines={1} style={styles.vaccineName}>{item.vaccine}</Text></View><Ionicons name="chevron-forward" size={20} color="#899397" /></View>
      <View style={[styles.vaccineMeta, compact && styles.vaccineMetaCompact]}><View style={[styles.metaItem, compact && styles.metaItemCompact]}><MaterialCommunityIcons name="calendar-month-outline" size={17} color={ORANGE} /><View><Text style={styles.metaLabel}>{item.status === 'Completed' ? 'Administered' : 'Due Date'}</Text><Text style={styles.metaValue}>{item.administeredDate || item.dueDate}</Text></View></View><View style={[styles.metaItem, compact && styles.metaItemCompact]}><MaterialCommunityIcons name="needle" size={17} color={ORANGE} /><View><Text style={styles.metaLabel}>Dose / Method</Text><Text style={styles.metaValue}>{item.dose} · {item.method}</Text></View></View>{actionable && <Pressable onPress={(event) => { event.stopPropagation?.(); onMarkGiven(item); }} style={({ pressed }) => [styles.givenButton, compact && styles.givenButtonCompact, pressed && styles.pressed]}><MaterialCommunityIcons name="check" size={16} color="#fff" /><Text style={styles.givenText}>Mark Given</Text></Pressable>}</View>
    </Pressable>
  );
}

export default function VaccinationManagementScreen({ vaccinations = DEFAULT_VACCINATIONS, addedHealthRecords = [], initialBird = null, onVaccinationsChange, onBack, onRecordVaccination }) {
  const { width } = useWindowDimensions(); const compact = width < 480; const narrow = width < 380;
  const [query, setQuery] = useState(initialBird?.name || ''); const [filter, setFilter] = useState('All');
  const addedVaccinations = useMemo(() => addedHealthRecords.filter((record) => record.type === 'Vaccination').map((record) => ({ id: record.id, name: record.name, breed: record.breed, image: record.image, vaccine: record.title, dose: record.careGiven, method: 'Recorded care', dueDate: record.recordedDate, administeredDate: record.recordedDate, administeredBy: record.recordedBy, status: 'Completed' })), [addedHealthRecords]);
  const allVaccinations = useMemo(() => [...addedVaccinations, ...vaccinations], [addedVaccinations, vaccinations]);
  const visible = useMemo(() => { const normalized = query.trim().toLowerCase(); return allVaccinations.filter((item) => { const filterMatch = filter === 'All' || filter === 'Due' && ['Due', 'Overdue'].includes(item.status) || item.status === filter; const queryMatch = `${item.name} ${item.breed} ${item.vaccine} ${item.status}`.toLowerCase().includes(normalized); return filterMatch && queryMatch; }); }, [allVaccinations, filter, query]);
  const dueCount = allVaccinations.filter((item) => ['Due', 'Overdue'].includes(item.status)).length;
  const upcomingCount = allVaccinations.filter((item) => item.status === 'Upcoming').length;
  const completedCount = allVaccinations.filter((item) => item.status === 'Completed').length;
  const markGiven = (item) => onVaccinationsChange(vaccinations.map((record) => record.id === item.id ? { ...record, status: 'Completed', administeredDate: 'Sep 1, 2026', administeredBy: 'Maria Santos' } : record));
  const openRecord = (item) => Alert.alert(item.vaccine, `${item.name}\n${item.status === 'Completed' ? `Administered ${item.administeredDate}` : `Due ${item.dueDate}`}\n${item.dose} - ${item.method}${item.batchNumber ? `\nBatch ${item.batchNumber}` : ''}`);
  return (
    <View style={styles.screen}><StatusBar style="light" translucent backgroundColor="transparent" /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.pageWrap}><View style={styles.page}>
      <View style={[styles.hero, compact && styles.heroCompact]}><Image source={HEALTH_HERO_IMAGE} style={StyleSheet.absoluteFill} contentFit="cover" contentPosition="center" cachePolicy="memory-disk" /><LinearGradient colors={['rgba(2,7,9,0.18)', 'rgba(2,7,9,0.3)', '#03090c']} locations={[0, 0.48, 1]} style={StyleSheet.absoluteFill} /><SafeAreaView edges={['top']} style={styles.heroSafeArea}><View style={styles.heroHeader}><View style={styles.heroHeaderLeft}><HeaderButton icon="arrow-back" label="Back to health and care" onPress={onBack} /><Text style={styles.screenTitle}>Vaccination Management</Text></View><HeaderButton icon="ellipsis-horizontal" label="Vaccination options" onPress={() => Alert.alert('Vaccination options', 'Manage vaccine schedules and reminders here.')} /></View><View style={[styles.heroCopy, narrow && styles.heroCopyNarrow]}><Text style={[styles.farmName, narrow && styles.farmNameNarrow]}>FarmBuzz Farm</Text><Text style={styles.heroSubtitle}>Track vaccine schedules and completed doses across the flock.</Text></View></SafeAreaView></View>
      <View style={[styles.content, narrow && styles.contentNarrow]}>
        <View style={[styles.actionRow, compact && styles.actionRowCompact]}><View style={styles.searchBox}><Ionicons name="search" size={20} color="#929da1" /><TextInput value={query} onChangeText={setQuery} placeholder="Search birds or vaccines..." placeholderTextColor="#7c888c" selectionColor={ORANGE} style={styles.searchInput} />{!!query && <Pressable onPress={() => setQuery('')} hitSlop={8}><Ionicons name="close-circle" size={18} color="#6c777b" /></Pressable>}</View><Pressable accessibilityLabel="Record vaccination" onPress={onRecordVaccination} style={({ pressed }) => [styles.recordButton, compact && styles.recordButtonCompact, pressed && styles.pressed]}><Ionicons name="add" size={24} color="#fff" />{!compact && <Text style={styles.recordButtonText}>Record Vaccination</Text>}</Pressable></View>
        <View style={styles.summary}><SummaryCard icon="alert-outline" value={String(dueCount)} label="Due Now" /><SummaryCard icon="calendar-clock-outline" value={String(upcomingCount)} label="Upcoming" /><SummaryCard icon="check-decagram-outline" value={String(completedCount)} label="Completed" isLast /></View>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{FILTERS.map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.filterActive]}><Text style={[styles.filterText, filter === item && styles.filterTextActive]}>{item}</Text><Text style={[styles.filterCount, filter === item && styles.filterTextActive]}>{item === 'All' ? allVaccinations.length : item === 'Due' ? dueCount : item === 'Upcoming' ? upcomingCount : completedCount}</Text></Pressable>)}</ScrollView>
        <View style={styles.sectionHeading}><Text style={styles.sectionTitle}>{filter === 'Completed' ? 'Vaccination History' : 'Vaccination Schedule'}</Text><Text style={styles.sectionCount}>{visible.length} records</Text></View>
        <View style={styles.vaccineList}>{visible.map((item) => <VaccinationRow key={item.id} item={item} compact={compact} onMarkGiven={markGiven} onOpen={openRecord} />)}{!visible.length && <View style={styles.empty}><MaterialCommunityIcons name="needle-off" size={32} color="#687478" /><Text style={styles.emptyTitle}>No vaccination records found</Text><Text style={styles.emptyText}>Try another filter or record a new vaccination.</Text></View>}</View>
        <View style={styles.reminder}><View style={styles.reminderIcon}><MaterialCommunityIcons name="bell-ring-outline" size={22} color={ORANGE} /></View><View style={styles.reminderCopy}><Text style={styles.reminderTitle}>Vaccination reminders are active</Text><Text style={styles.reminderText}>Due and overdue records are included in Health & Care alerts.</Text></View></View>
      </View>
    </View></ScrollView></View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#020709' }, pageWrap: { flexGrow: 1, alignItems: 'center', backgroundColor: '#020709' }, page: { width: '100%', maxWidth: 720, backgroundColor: '#020709' }, hero: { height: 275, overflow: 'hidden', backgroundColor: '#101719' }, heroCompact: { height: 255 }, heroSafeArea: { flex: 1 }, heroHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingTop: Platform.OS === 'web' ? 10 : 3 }, heroHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 }, headerButton: { width: 40, height: 40, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(190,204,208,0.35)', backgroundColor: 'rgba(2,8,11,0.65)', alignItems: 'center', justifyContent: 'center' }, screenTitle: { color: '#f1f3f3', fontSize: 17, fontWeight: '700' }, heroCopy: { marginTop: 'auto', paddingHorizontal: 18, paddingBottom: 24 }, heroCopyNarrow: { paddingHorizontal: 11, paddingBottom: 18 }, farmName: { color: '#f5f6f6', fontSize: 32, lineHeight: 38, fontWeight: '800', fontFamily: Platform.select({ ios: 'Georgia', android: 'serif', web: 'Georgia' }), textShadowColor: 'rgba(0,0,0,0.72)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 5 }, farmNameNarrow: { fontSize: 27, lineHeight: 32 }, heroSubtitle: { maxWidth: 470, marginTop: 5, color: '#bac2c4', fontSize: 12, lineHeight: 18 },
  content: { paddingHorizontal: 10, paddingBottom: 28 }, contentNarrow: { paddingHorizontal: 8 }, actionRow: { flexDirection: 'row', gap: 9 }, actionRowCompact: { flexDirection: 'row', gap: 8 }, searchBox: { flex: 1, height: 52, paddingHorizontal: 14, borderWidth: 1, borderColor: '#28353a', borderRadius: 8, backgroundColor: '#0a1317', flexDirection: 'row', alignItems: 'center', gap: 9 }, searchInput: { flex: 1, height: 50, paddingVertical: 0, color: '#e4e8e9', fontSize: 12, outlineStyle: 'none' }, recordButton: { minWidth: 178, height: 52, paddingHorizontal: 16, borderRadius: 8, backgroundColor: '#f66f00', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, recordButtonCompact: { width: 52, minWidth: 52, paddingHorizontal: 0 }, recordButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  summary: { minHeight: 104, marginTop: 10, borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317', flexDirection: 'row', overflow: 'hidden' }, summaryCard: { flex: 1, minWidth: 0, padding: 8, alignItems: 'center', justifyContent: 'center' }, summaryDivider: { borderRightWidth: 1, borderRightColor: '#223037' }, summaryIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,122,0,0.09)', alignItems: 'center', justifyContent: 'center' }, summaryValue: { marginTop: 5, color: '#eef1f2', fontSize: 20, fontWeight: '800' }, summaryLabel: { marginTop: 3, color: '#899599', fontSize: 9, textAlign: 'center' }, filters: { minWidth: '100%', paddingTop: 12, paddingBottom: 2, gap: 7 }, filter: { minWidth: 96, height: 40, paddingHorizontal: 11, borderWidth: 1, borderColor: '#28353a', borderRadius: 7, backgroundColor: '#0a1317', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, filterActive: { borderColor: ORANGE, backgroundColor: 'rgba(255,122,0,0.08)' }, filterText: { color: '#8d999c', fontSize: 10, fontWeight: '600' }, filterTextActive: { color: ORANGE }, filterCount: { color: '#687478', fontSize: 8 },
  sectionHeading: { minHeight: 52, paddingTop: 19, paddingBottom: 8, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' }, sectionTitle: { color: '#e7eaeb', fontSize: 15, fontWeight: '700' }, sectionCount: { color: ORANGE, fontSize: 9, fontWeight: '700' }, vaccineList: { gap: 8 }, vaccineCard: { borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317', overflow: 'hidden' }, vaccineTop: { minHeight: 76, padding: 9, flexDirection: 'row', alignItems: 'center', gap: 10 }, birdImage: { width: 52, height: 52, borderRadius: 8, backgroundColor: '#111a1e' }, vaccineCopy: { flex: 1, minWidth: 0 }, nameRow: { flexDirection: 'row', alignItems: 'center', gap: 7 }, birdName: { flex: 1, color: '#e8ebec', fontSize: 12, fontWeight: '800' }, birdBreed: { marginTop: 3, color: '#7f8b8f', fontSize: 8 }, vaccineName: { marginTop: 6, color: '#c7ced0', fontSize: 10, fontWeight: '700' }, statusBadge: { minHeight: 24, paddingHorizontal: 7, borderWidth: 1, borderColor: '#6b420f', borderRadius: 12, backgroundColor: 'rgba(255,122,0,0.08)', alignItems: 'center', justifyContent: 'center' }, statusCompleted: { borderColor: '#414a4d', backgroundColor: '#171e20' }, statusText: { color: ORANGE, fontSize: 7, fontWeight: '800' }, vaccineMeta: { minHeight: 60, paddingHorizontal: 10, paddingVertical: 8, borderTopWidth: 1, borderTopColor: '#223037', flexDirection: 'row', alignItems: 'center', gap: 14 }, vaccineMetaCompact: { flexWrap: 'wrap', gap: 8 }, metaItem: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 7 }, metaItemCompact: { flexBasis: '46%' }, metaLabel: { color: '#6f7c80', fontSize: 7 }, metaValue: { marginTop: 3, color: '#b6bec0', fontSize: 8 }, givenButton: { height: 34, paddingHorizontal: 9, borderRadius: 7, backgroundColor: '#f66f00', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4 }, givenButtonCompact: { width: '100%' }, givenText: { color: '#fff', fontSize: 8, fontWeight: '700' }, cardPressed: { opacity: 0.78 },
  empty: { minHeight: 180, borderWidth: 1, borderColor: '#26343a', borderRadius: 8, backgroundColor: '#0a1317', alignItems: 'center', justifyContent: 'center' }, emptyTitle: { marginTop: 10, color: '#d7dcde', fontSize: 12, fontWeight: '700' }, emptyText: { marginTop: 5, color: '#778387', fontSize: 9 }, reminder: { minHeight: 70, marginTop: 12, padding: 10, borderWidth: 1, borderColor: '#5f3b0f', borderRadius: 8, backgroundColor: 'rgba(255,122,0,0.05)', flexDirection: 'row', alignItems: 'center', gap: 10 }, reminderIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: 'rgba(255,122,0,0.1)', alignItems: 'center', justifyContent: 'center' }, reminderCopy: { flex: 1 }, reminderTitle: { color: '#e0e4e5', fontSize: 10, fontWeight: '700' }, reminderText: { marginTop: 4, color: '#7f8b8f', fontSize: 8, lineHeight: 12 }, pressed: { opacity: 0.72 },
});
